jaegertracing/jaeger-operator

.travis.yml, Dockerfile, Makefile, RELEASE.adoc, test/e2e/jaeger_test.go, test/e2e/main_test.go, test/e2e/production_test.go
=> Reuse the same ES for all tests

.travis/after_success.sh, .travis/install.sh
=> Release Docker image upon merge to master

.travis/after_success.sh, .travis/script.sh, Dockerfile
=> Fix publishing of release

.travis/after_success.sh, Makefile, jaeger.version, pkg/cmd/start/main.go, pkg/cmd/version/main.go, pkg/controller/all-in-one_test.go, pkg/controller/production_test.go, pkg/deployment/agent.go, pkg/deployment/agent_test.go, pkg/deployment/all-in-one.go, pkg/deployment/all-in-one_test.go, pkg/deployment/collector.go, pkg/deployment/collector_test.go, pkg/deployment/query.go, pkg/deployment/query_test.go, pkg/version/main.go
=> Support Jaeger version and image override

README.adoc
=> Add instructions on how to run the operator on OpenShift

README.adoc
=> Remove work in progress notice

.travis.yml, .travis/publish-images.sh, RELEASE.adoc
=> Fix docker push command and update release instructions

README.adoc, deploy/examples/all-in-one-with-options.yaml, jaeger.version
=> Bump Jaeger to 1.7

.travis/release.sh, CHANGELOG.adoc, README.adoc, deploy/examples/all-in-one-with-options.yaml, jaeger.version
=> Add changelog

CHANGELOG.adoc
=> Fix changelog 'new features' header for 1.8

CHANGELOG.adoc, README.adoc, RELEASE.adoc
=> Prepare for release v1.8.1

CHANGELOG.adoc
=> Prepare for release v1.8.2

README.adoc
=> Fix secrets readme

pkg/deployment/collector_test.go
Travis is currently failing on this, after merging #145
=> Fix import order for collector-test

README.adoc, deploy/examples/all-in-one-with-options.yaml, jaeger.version
=> Update jaeger version to 1.9

deploy/examples/simple-streaming.yaml
=> Remove debug logging from simple-streaming example

CONTRIBUTING.adoc
Fixes #189 by improving the documentation on namespaces vs. OpenShift.
=> Added mention to WATCH_NAMESPACE when running for OpenShift

CHANGELOG.adoc
=> Prepare for v1.9.2

README.adoc, deploy/examples/all-in-one-with-options.yaml, jaeger.version
Similar to https://github.com/jaegertracing/jaeger-operator/pull/176/files
=> Bump Jaeger to 1.10

CHANGELOG.adoc
=> Prepare for v1.10.0

pkg/apis/io/v1alpha1/jaeger_types.go, pkg/controller/jaeger/jaeger_controller.go, pkg/controller/jaeger/status/collector.go, pkg/controller/jaeger/status/collector_test.go
Closes #248 by adding the sum of key metrics to the `JaegerStatus` object.
=> Added metrics to JaegerStatus object

Makefile, test/e2e/cassandra.go, test/e2e/es_index_cleaner_test.go, test/e2e/production_test.go, test/e2e/spark_dependencies_test.go, test/e2e/utils.go
Signed-off-by: Kevin Earls <kearls@kevinearls.com>
=> Fix ES and Cassandra tests which were failing on OpenShift

pkg/controller/jaeger/dependencies.go, pkg/controller/jaeger/deployment.go, pkg/controller/jaeger/elasticsearch.go
=> Block until objects have been created and are ready

Makefile
=> Fix clean storage goal

Makefile
Related to https://github.com/jaegertracing/jaeger-operator/pull/275/files#r263380911
=> Use current namespace for storage

pkg/deployment/agent.go
=> Enable agent readiness probe

pkg/deployment/agent.go
=> Change agent reporter to GRPC

pkg/apis/jaegertracing/v1/options.go
=> Remove unused error

pkg/storage/elasticsearch.go, pkg/storage/elasticsearch_test.go
=> Set default query timeout for provisioned ES

pkg/deployment/agent.go
=> Fix reporter type flag

test/e2e/suite_elasticsearch_test.go
Resolves #178 
This is currently working for me on both minikube and minishift/
=> Restore es-index-cleaner test

Makefile, test/e2e/self_provisioned_elasticsearch.go, test/e2e/suite_self_provisioned_elasticsearch_test.go
=> Add e2e test for self provisioned Elasticsearch

Makefile, pkg/controller/jaeger/elasticsearch.go, test/e2e/self_provisioned_elasticsearch.go, test/e2e/suite_self_provisioned_elasticsearch_test.go
=> Add self provisioned ES test to main e2e goal

.travis/release.sh, CONTRIBUTING.adoc, Makefile
=> Update references to the changed CSV filename

.travis.yml, .travis/rune2eTests.sh, .travis/setupMinikube.sh, Makefile
=> Enable running e2e tests on a per PR basis on Travis

Makefile
=> Add verbose option for running test, set EV to consolidate other options

Makefile
=> Allow skipping docker build for pipeline jobs

Makefile
=> Add streaming e2e target

CHANGELOG.adoc
=> Change log for jaeger-operator 1.12.0

deploy/operator.yaml
=> Short term fix for missing 1.12.0 tag on dockerhub

README.adoc
=> Add GoDoc badge

deploy/olm-catalog/jaeger.clusterserviceversion.yaml, deploy/operator-group.yaml
=> Revert csv namespace to placeholder and remove operator-group.yaml

pkg/cmd/start/main.go
This PR is a workaround for #461. A real solution is still not known.
=> Removed 'expose metrics port' to prevent 'failed to create or get service' error

CHANGELOG.adoc
=> Prepare for v1.12.1

test/e2e/self_provisioned_elasticsearch_test.go
=> Revert incorrect part of PR 480; skip test until issue481 is fixed

test/e2e/spark_dependencies_test.go
=> Improve error messages; remove unused code

CHANGELOG.adoc
=> Prepare for v1.13.0

CHANGELOG.adoc
=> Update changelog for v1.13.1

pkg/storage/elasticsearch.go, pkg/storage/elasticsearch_test.go
=> Set the ES node GenUUID to explicit value

test/e2e/daemonset_test.go, test/e2e/wait_util.go
=> Fix the daemonset test to work after pr346 changes

test/e2e/all_in_one_test.go, test/e2e/cassandra_test.go, test/e2e/daemonset_test.go, test/e2e/elasticsearch_test.go, test/e2e/self_provisioned_elasticsearch_test.go, test/e2e/sidecar_test.go, test/e2e/spark_dependencies_test.go, test/e2e/streaming_test.go, test/e2e/utils.go
=> Update tests to undeploy Jaeger instance at end

deploy/operator.yaml
=> Reverted change to the operator's image

go.mod
=> Fix the go.mod

pkg/storage/elasticsearch.go
=> Change replace method, to remain compatible with golang 1.11

README.adoc
Simple documentation for the ES Cleaner Job
=> Added documentation for es cleaner job

jaeger.version
=> Change jaeger.version file to use major.minor.patch version

deploy/olm-catalog/jaeger.clusterserviceversion.yaml, deploy/role.yaml, pkg/cmd/start/main.go, test/role.yaml
Fixes #461 by adding the required rule in the role.yaml file.
=> Reinstated the service metrics

.travis.yml, .travis/rune2eTests.sh, .travis/setupOpenShift.sh, deploy/role.yaml, test/role.yaml
=> Run ES self provisioned e2e test on travis using OCP 3.9

Makefile
=> Add cleanup targets for CI jobs

test/e2e/all_in_one_test.go, test/e2e/cassandra_test.go, test/e2e/daemonset_test.go, test/e2e/elasticsearch_test.go, test/e2e/port_forward.go, test/e2e/self_provisioned_elasticsearch_test.go, test/e2e/sidecar_test.go, test/e2e/streaming_test.go, test/e2e/utils.go
=> Use random ports when port forwarding

.travis/publish-images.sh
=> Added push of container images to quay

.travis/publish-images.sh
=> Fixed pushing of images to Docker Hub

Makefile, test/e2e/self_provisioned_elasticsearch_test.go
=> Add test to validate elasticsearch-operator image

pkg/controller/jaeger/jaeger_controller.go
Fixes #557. This change is because handleFinalizer does an update (for add or remove the finalizer), so it overrides the APIVersion and Kind fields with empty strings.
=> Check and update finalizers before setting APIVersion and Kind

.travis/release.sh
=> Fixed the release script to work with M.m.p.o

deploy/examples/simple-prod-with-volumes.yaml, deploy/examples/simple-prod.yaml, deploy/examples/simple-streaming.yaml, deploy/examples/with-cassandra.yaml
=> Minor fixes to get examples working

deploy/olm-catalog/jaeger.package.yaml
=> Change OLM catalog package channel to stable

test/e2e/elasticsearch_test.go
=> Add test for elasticsearch index prefixes

Makefile, test/e2e/all_in_one_test.go, test/e2e/cassandra_test.go, test/e2e/daemonset_test.go, test/e2e/examples_test.go, test/e2e/misc_test.go, test/e2e/port_forward.go, test/e2e/self_provisioned_elasticsearch_test.go, test/e2e/sidecar_test.go, test/e2e/simplest_test.go, test/e2e/smoketest.go, test/e2e/spark_dependencies_test.go, test/e2e/utils.go
=> Add format verification for tests, and apply it

.github/workflows/master.yaml, Makefile
=> Added basic workflow

Makefile
=> Changed how we skip the 'docker push' for CIs

.ci/run-e2e-tests.sh, .github/workflows/e2e-kubernetes.yaml, Makefile, test/e2e/examples1_test.go, test/e2e/examples2_test.go, test/e2e/utils.go
=> Divide examples to speed up ci

pkg/strategy/controller.go, pkg/strategy/controller_test.go
Resolves https://issues.jboss.org/browse/TRACING-682
=> Add Jaeger version to Elasticsearch job images

pkg/account/const.go, pkg/apis/jaegertracing/v1/jaeger_types.go, pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go, pkg/cronjob/spark_dependencies.go, pkg/cronjob/spark_dependencies_test.go
=> Add common spec to dependencies

.ci/release.sh, .github/workflows/release.yaml
=> Disabled releasing on master

deploy/examples/with-badger-and-volume.yaml, deploy/olm-catalog/jaeger.clusterserviceversion.yaml
=> Adjusted the ALM examples and operator capabilities in CSV

README.md
=> Updated CI badge to show the workflow

test/e2e/smoketest.go, test/e2e/streaming_test.go, test/e2e/wait_util.go
=> Add a streaming test which uses TLS

go.mod
https://blog.golang.org/using-go-modules
=> Add golang version to go.mod

pkg/apis/jaegertracing/v1/jaeger_types.go, pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go, pkg/cronjob/spark_dependencies.go, pkg/cronjob/spark_dependencies_test.go
Related to https://github.com/jaegertracing/jaeger-operator/issues/668#issuecomment-543698875
PR in spark-dependencies https://github.com/jaegertracing/spark-dependencies/pull/79
=> Pass only specified options to spark dependencies

.ci/upload-test-coverage.sh, .github/workflows/base-checks.yaml
=> Reinstated codecov

test/e2e/streaming_test.go
Signed-off-by: Kevin Earls <kearls@redhat.com>  This is the first part of #713
=> Update test to use new KafkaUser type

pkg/upgrade/v1_15_0.go, pkg/upgrade/v1_15_0_test.go, pkg/upgrade/versions.go
=> Upgrade deprecated flags from 1.14 and previous, to 1.15

test/e2e/all_in_one_test.go, test/e2e/sidecar_test.go, test/e2e/utils.go
Most of our tests use port mapping to connect to Jaeger query api or to create traces.  Unfortunately this is sometimes a bit flaky, so as an experiment I am updating the sidecar test (which seems to have this issue most frequently) to use ingress instead.  If this resolves that problem, I will add it to additional tests.
=> Use ingress instead of port mapping for sidecar test

pkg/inject/sidecar.go
Missed the agent sidecar image when doing https://github.com/jaegertracing/jaeger-operator/pull/743.
=> Use util function for Image name in agent sidecar

CHANGELOG.md, versions.txt
=> Update changelog for v1.15.0

.ci/release.sh, .github/workflows/release.yaml
Related to #751, to release 1.15.0
=> Fixes to the release script

.ci/release.sh
=> Added user.name and user.email to the git config in the release script

pkg/cronjob/es_index_cleaner.go, pkg/cronjob/es_rollover.go, pkg/cronjob/es_rollover_test.go, pkg/cronjob/spark_dependencies.go, pkg/cronjob/spark_dependencies_test.go, pkg/storage/elasticsearch_dependencies.go, pkg/storage/elasticsearch_dependencies_test.go, pkg/strategy/controller.go, pkg/strategy/controller_test.go, pkg/util/util.go, pkg/util/util_test.go
Resolves #471
and part of #592 
docs PR https://github.com/jaegertracing/documentation/pull/324
=> Support TLS in Elasticsearch cron jobs

.ci/release.sh
This PR fixes the two places in the generated CSV that need manual fixing during the last release. First, by moving the `gen-csv` to execute after the versions in the `operator.yaml` are changed. And second, by bumping the `containerImage` field in the generated CSV, as it seems that it's copied over from the previous CSV.
=> Replace the containerImage version in the generated CSV

.ci/release.sh
=> Revert the inlining of commit author

RELEASE.md
=> Updated release procedure

deploy/olm-catalog/jaeger-operator/1.15.1/jaeger-operator.v1.15.1.clusterserviceversion.yaml
Main change is to remove the unused examples. The list is intended to show the simplest (most basic) CR for each CRD owned by this operator. So all but the first are actually included in the operator UI.
The other changes are minor wording improvements.
=> CSV changes to be picked up for next release

test/e2e/all_in_one_test.go
This test fails intermittently because of request timeouts, so here I have increased the timeout, and also changed the wait loop to retry instead of failing if we still get timeouts.
I've also made a few changes where I call require.NoError rather than returning the error, as this gives better information in the case of failures.
=> Retry http request after timeout to avoid intermittent test failure

.ci/format.sh, Makefile
=> Use GOPATH instead of hardcoded path for format task

.ci/publish-images.sh, .github/workflows/publish-images.yaml
=> Fixed the publishing of master images

test/e2e/examples1_test.go, test/e2e/self_provisioned_elasticsearch_test.go
=> Add test case to increasing replicas

deploy/examples/with-badger-and-volume.yaml
=> Fixed the with-badger-and-volume example

.devbots/needs-triage.yml, .github/stale.yml
Related to jaegertracing/jaeger#1977
=> Added configuration for stale bot and needs-triage

test/e2e/spark_dependencies_test.go
=> Increase timeouts to avoid intermittent test failures

test/e2e/examples1_test.go, test/e2e/utils.go
This is the same case as #857 except here it occurs when we test the example.
=> Increase timeout for cassandra example

test/e2e/streaming_test.go
=> Add test for Kafka auto provisioning

test/e2e/self_provisioned_elasticsearch_kafka_test.go
These are the same changes I made for the streaming_test in https://github.com/jaegertracing/jaeger-operator/pull/868.  It's more accurate, and will also give us better information in case of failures.
=> Add waitfors for kafka and zookeeper instances

deploy/crds/jaegertracing.io_jaegers_crd.yaml, pkg/apis/jaegertracing/v1/jaeger_types.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Verification
```
kubectl get jaeger
NAME                              STATUS    VERSION   STRATEGY   STORAGE   AGE
jaeger-all-in-one-inmemory        Running   1.16.0    allinone   memory    62s
jaeger-all-in-one-local-storage   Running   1.16.0    allinone   badger    17s
```
=> Add additional printer columns

CHANGELOG.md, deploy/examples/auto-provision-kafka.yaml, pkg/storage/elasticsearch.go, pkg/storage/elasticsearch_test.go, pkg/strategy/streaming.go, pkg/upgrade/migrate_deprecated.go, pkg/upgrade/migrate_deprecated_test.go, pkg/upgrade/v1_15_0.go, pkg/upgrade/v1_15_0_test.go, pkg/upgrade/v1_17_0.go, pkg/upgrade/v1_17_0_test.go, pkg/upgrade/versions.go, versions.txt
=> Prepare for v1.17.0

deploy/examples/simple-streaming.yaml, test/e2e/streaming_test.go
=> Update tests to cover new Kafka CLI flags

Makefile
=> Reduce pvc usage by standard kafka example

CHANGELOG.md, Makefile, RELEASE.md, pkg/upgrade/versions.go, versions.txt
=> Preparing release 1.17.1

RELEASE.md
=> Document waiting on release CI job

test/e2e/cassandra_test.go, test/e2e/examples1_test.go, test/e2e/utils.go
=> Skip cassandra tests on openshift

test/e2e/sidecar_test.go
=> Fixed wait-for-deployment in sidecar test

Makefile, test/e2e/examples1_test.go
=> Remove test that requires deploying es-operator

test/e2e/examples1_test.go
=> Switch to non-cached client to avoid intermittent failures

Makefile, test/e2e/examples_openshift_test.go
=> Add separate test suite for openshift only examples

Makefile, test/e2e/elasticsearch_token_propagation_test.go
=> Update e2e token tests

.ci/start-minikube.sh, test/e2e/examples2_test.go, test/e2e/misc_test.go, test/e2e/utils.go
=> Add option to save operator and operand logs

test/e2e/utils.go
The initial change I submitted yesterday would only work correctly for all-in-one instances
=> Fix saving logs for non all-in-one instances

test/e2e/misc_test.go
=> Ignore 503s to avoid intermittent test failure

test/e2e/smoketest.go
=> Retry after http request failure

test/e2e/elasticsearch_token_propagation_test.go
=> Retry request after 503

test/e2e/utils.go
=> Fix way logfilenamebase is created

test/e2e/examples1_test.go, test/e2e/smoketest.go
=> Retry if update of vertx deployment fails

test/e2e/misc_test.go, test/e2e/smoketest.go, test/e2e/utils.go
=> Add new test for issue 670

Makefile
=> Fail build if kafka example does not download or is invalid

test/e2e/wait_util.go
=> Fix typo in godoc

test/e2e/misc_test.go, test/e2e/utils.go
=> Update TestDeleteResource to work with OLM installed operators

test/e2e/elasticsearch_token_propagation_test.go
=> Fix token propagation test to work for OLM

pkg/account/main.go, pkg/account/main_test.go
Signed-off-by: Adrie van Dijk <adrie.van.dijk@minienw.nl>
=> Missing components added to func JaegerServiceAccountFor()

Makefile
=> Use ES operator 4.4

Makefile
=> Allow overrideing prometheus crds 

.ci/run-e2e-tests.sh, .github/workflows/e2e-kubernetes.yaml, test/e2e/elasticsearch_test.go, test/e2e/self_provisioned_elasticsearch_kafka_test.go, test/e2e/self_provisioned_elasticsearch_test.go, test/e2e/smoketest.go, test/e2e/streaming_test.go, test/e2e/utils.go
=> Update tests to run with jaeger and otel collectors

CHANGELOG.md, versions.txt
=> Preparing release v1.18.0

.ci/.operatorhub-pr-template.md
=> Update operator hub PR template

test/e2e/streaming_test.go
=> Use correct namespace when checking image

CHANGELOG.md, versions.txt
=> Preparing release 1.18.1

pkg/config/ca/ca.go, pkg/util/util.go, pkg/util/util_test.go
=> Fix duplicate mount path for /etc/pki/ca-trust/extracted/pem

.ci/operatorhub.sh
=> Updated operatorhub.sh to use the new CSV location

test/e2e/daemonset_test.go
=> Changed agent-as-daemonset image for the jaeger-agent

test/e2e/elasticsearch_test.go, test/e2e/self_provisioned_elasticsearch_kafka_test.go, test/e2e/self_provisioned_elasticsearch_test.go, test/e2e/sidecar_namespace_test.go, test/e2e/sidecar_test.go, test/e2e/streaming_test.go, test/e2e/utils.go
NOTE: I meant to mark this as WIP.  Do not merge this yet.
=> Add otel test options

pkg/inject/sidecar.go, pkg/inject/sidecar_test.go
=> Added 'w3c' to the injected JAEGER_PROPAGATION env var

.ci/run-e2e-tests.sh, .github/workflows/e2e-kubernetes.yaml
=> Run the smoke tests with otel agent and all-in-one

pkg/controller/deployment/deployment_controller.go, pkg/controller/namespace/namespace_controller.go
This is an attempt to stabilize the injection mechanism, before this patch we created a new sidecar and compare the new sidecar with the old one. The issue with this approach is the function that creates the sidecar uses the length of `dep.Spec.Template.Spec.Containers` to derive part of the arguments (See https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/inject/sidecar.go#L198) . So in the first reconciliation process it inject one sidecar, but the next reconciliation process will inject a different sidecar with an extra argument. This triggers the pod re-creation process twice.
This approach recreated the sidecar in each deployment reconciliation 
This also uses patch instead of update in an effort to alleviate some errors related to the version of the resource.
Fixes …
=> Completely replace the sidecar on each reconciliation, call patch instead of update.

test/e2e/streaming_test.go
=> Don't set kafka batch options when using otel collector

deploy/examples/ingress-with-annotation.yaml, deploy/examples/ingress-with-host.yaml
Signed-off-by: Prageeth Warnak <prageeth.warnak@team.telstra.com>
=> adding samples for ingress hosts and annotations

.ci/operatorhub.sh
=> Updated the Operator Hub PR template

Makefile, test/e2e/autoscale_test.go
=> Add autoscale test for ingester

pkg/controller/namespace/namespace_controller.go, pkg/upgrade/v1_20_0.go, pkg/upgrade/v1_20_0_test.go
=> Run make format

.github/mergify.yml
=> Set mergify to dismiss stale reviews

test/e2e/daemonset_test.go, test/e2e/examples1_test.go
=> Update openshift only tests with new location of examples

test/e2e/generator_test.go
=> Skip generator test until issue 1278 if resolved

test/e2e/autoscale_test.go, test/e2e/elasticsearch_test.go, test/e2e/self_provisioned_elasticsearch_kafka_test.go, test/e2e/self_provisioned_elasticsearch_test.go, test/e2e/sidecar_test.go, test/e2e/streaming_test.go
i.e. when using 2.0 and running with SPECIFY_OTEL_ONFIG set to true
=> Fix these tests to work properly when using OTEL images

.github/workflows/base-checks.yaml, .github/workflows/e2e-kubernetes.yaml, .github/workflows/release.yaml, deploy/crds/jaegertracing.io_jaegers_crd.yaml, examples/operator-with-tracing.yaml
=> Bump actions to latest versions

CHANGELOG.md, versions.txt
=> Preparing relase 1.21.0

.github/workflows/release.yaml
=> Fix release github workflow, setup buildx

CHANGELOG.md
=> Preparing relase 1.21.1

.ci/release.sh, versions.txt
=> Release script only bump operator version in versions.txt

CHANGELOG.md
=> Preparing relase 1.21.2

test/e2e/examples1_test.go
This should have been included with #1259
=> Allow overriding vertx image when testing examples

Makefile, test/e2e/autoscale_test.go, test/e2e/elasticsearch_test.go, test/e2e/elasticsearch_token_propagation_test.go, test/e2e/examples2_test.go, test/e2e/self_provisioned_elasticsearch_kafka_test.go, test/e2e/streaming_test.go, test/e2e/utils.go
=> Enable running tests without an external ES instance

go.mod, go.sum
Fix #1326 
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>
=> Fix unstable mod tidy

build/Dockerfile
Based on https://github.com/jaegertracing/jaeger-operator/issues/1336#issue-760280621
=> set non root group

.github/workflows/release.yaml
=> Fix release action, set operator sdk

.ci/.operatorhub-pr-template.md, .ci/operatorhub.sh
=> Update operatorhub PR template

examples/simplest.yaml
=> simplest example file should be as simplest

.ci/install-kuttl.sh, .github/workflows/e2e-kuttl.yaml, .gitignore, Makefile, kuttl-test.yaml, tests/e2e/simplest/00-install.yaml, tests/e2e/simplest/01-assert.yaml
=> Configure e2e tests using kuttl, run simplest test

pkg/deployment/agent_test.go, pkg/deployment/all_in_one.go, pkg/deployment/all_in_one_test.go, pkg/deployment/collector.go, pkg/deployment/collector_test.go, pkg/upgrade/v1_22_0.go, pkg/upgrade/v1_22_0_test.go
Fixes https://github.com/jaegertracing/jaeger-operator/issues/1441
=> Migrate remaining flags and some env vars to 1.22

CHANGELOG.md, RELEASE.md, versions.txt
=> Preparing release v1.23.0

deploy/olm-catalog/jaeger-operator/jaeger-operator.package.yaml, deploy/olm-catalog/jaeger-operator/manifests/jaeger-operator.clusterserviceversion.yaml, deploy/operator.yaml, test/operator.yaml, versions.txt
=> Release v1.23.0

CHANGELOG.md, README.md, versions.txt
=> Preparing release v1.24.0

CHANGELOG.md, RELEASE.md, versions.txt
=> Preparing release v1.25.0

deploy/olm-catalog/jaeger-operator/manifests/jaeger-operator.clusterserviceversion.yaml
=> Add disconnected annotation to csv

.ci/create-release-github.sh, .ci/prepare-release.sh, .github/workflows/release.yaml, Makefile, RELEASE.md
=> Change release process

.ci/create-release-github.sh, .github/workflows/release.yaml
=> Use github token for release

README.md
=> Update readme to point to jaeger docs for install instructions

.ci/create-release-github.sh, .ci/operatorhub.sh, .ci/prepare-release.sh, .github/workflows/release.yaml, Makefile, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml
=> Update release process to align with new project structure

Makefile
=> Wait cluster before running scoreboard tests

CHANGELOG.md, RELEASE.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, versions.txt
=> Preparing release v1.29.0

.github/workflows/release.yaml
=> Add setupbuild and setup-qemu to release action

bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml
=> Fix CSV and manifest to use quay.io repository

Makefile
=> Fix dry-run arg in Makefile

bundle.Dockerfile, bundle/metadata/annotations.yaml
=> Fix OLM metadata

CHANGELOG.md, RELEASE.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, versions.txt
=> Preparing release v1.29.1

CHANGELOG.md, RELEASE.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, versions.txt
=> Preparing release v1.30.0

.github/workflows/e2e.yaml
- #1692
* Note: I know there is a typo in the rule of the rule but it will be fixed in #1715 *
=> Add missing E2E sidecar tests

Makefile
=> Remove unused e2e-tests prerequisite from test target

pkg/cmd/start/bootstrap.go
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
Great explanation is provided here https://issues.redhat.com/browse/TRACING-2407
=> Make operator more resiliant to etcd defrag activity

CHANGELOG.md, README.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, versions.txt
---
@pavolloffay Please review.
// cc : @rubenvp8510  @rkukura
=> Preparing release v1.32.0

tests/e2e/render-utils.sh
- #1822
-  Remove the usage of the `-n` argument. It was ignored previously
=> Fix xargs warning

pkg/inject/sidecar.go
- misleading comments
- removed lines of misleading commets
=> remove misleading comment about IncreaseRevision function

.github/workflows/release.yaml
=> Fix release action install steps

.github/workflows/e2e-elasticsearch.yaml, .github/workflows/e2e-examples.yaml, .github/workflows/e2e-generate.yaml, .github/workflows/e2e-miscellaneous.yaml, .github/workflows/e2e-sidecar.yaml, .github/workflows/e2e-streaming.yaml, .github/workflows/e2e-ui.yaml, .github/workflows/e2e-upgrade.yaml, hack/install/install-kind.sh, kind-1.24.yaml
=> Use Kubernetes 1.24 for E2E tests

hack/install/install-kuttl.sh
=> Upgrade KUTTL version

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, versions.txt
depends on https://github.com/jaegertracing/jaeger-operator/pull/1901
=> Preparing release v1.34.1

Makefile
- Resolves #1923
- Add missing parameter
=> Fix version in Docker container.

COMPATIBILITY.md
=> add 1.34.x to compatibility matrix

RELEASE.md
- Require running the tests as one of the steps to create a release.
=> Add running tests to README.md

hack/common.sh, tests/e2e/elasticsearch/es-multiinstance/03-create-second-instance.yaml.template, tests/e2e/elasticsearch/render.sh
=> Fix path to KUTTL in multiinstance test

hack/install/install-kind.sh, kind-1.19.yaml, kind-1.20.yaml, kind-1.21.yaml, kind-1.22.yaml, kind-1.23.yaml, kind-1.24.yaml
- Update kind
- Update kind version to use
- Update the container images to use for the K8s versions
=> Upgrade kind to 0.14.0 and the container images

tests/e2e/examples/render.sh
- Add E2E test for `all-in-one-with-options` example
=> Add E2E test for all-in-one-with-options example

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
=> Preparing release v1.36.0

pkg/storage/elasticsearch_dependencies.go
=> es-dependencies: support image pull secret

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
- https://github.com/jaegertracing/jaeger-operator/issues/2017
@iblancasa  as soon as the openshift test pass we can merge this.
//cc @pavolloffay
=> Preparing release v1.37.0

.ci/publish-images.sh, .github/workflows/release.yaml
=> Change docker credentials to use token

.github/workflows/publish-images.yaml
=> Use DOCKERHUB_TOKEN for publish images action

Makefile, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, bundle/manifests/jaegertracing.io_jaegers.yaml, bundle/tests/scorecard/config.yaml, config/crd/bases/jaegertracing.io_jaegers.yaml, config/default/manager_auth_proxy_patch.yaml, hack/install/install-controller-gen.sh
- Upgrade `operator-sdk` to 1.23.0
=> Upgrade operator-sdk to 1.23.0

pkg/cronjob/spark_dependencies.go, pkg/cronjob/spark_dependencies_test.go
- fixes #2016 
- set alias enable environment variable for spark cronjob
=> fix: set alias enable variable for spark cronjob

hack/install/install-kuttl.sh
=> Upgrade KUTTL version from 0.12.1 to 0.13.0

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
- Resolves https://github.com/jaegertracing/jaeger-operator/issues/2067
-  Preparation for release 1.38.0, update manifests, changelog etc..
=> Preparing release v1.38.0

pkg/deployment/otlp.go, pkg/service/collector.go
Signed-off-by: Karol Szwaj [karol.szwaj@gmail.com](mailto:karol.szwaj@gmail.com)
- https://github.com/jaegertracing/helm-charts/issues/344#issuecomment-1100166786 (partially)
- Reopening https://github.com/jaegertracing/jaeger-operator/pull/2018
=> Add http- prefix to otlp port names

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, tests/templates/assert-kafka-cluster.yaml.template, tests/templates/assert-zookeeper-cluster.yaml.template, tests/templates/openshift/report-spans.yaml.template, versions.txt
=> Preparing release v1.38.1

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
- Resolves https://github.com/jaegertracing/jaeger-operator/issues/2108
-  This PR is a preparation step for releasing operator 1.39.0, updates manifests and CHANGELOG.md
=> Preparing release v1.39.0

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
-  Resolves https://github.com/jaegertracing/jaeger-operator/issues/2135
-  CHANGELOG, version.txt and manifest updates for 1.40.0
=> Preparing release v1.40.0

bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/operator-with-tracing.yaml, versions.txt
-  Resolves #2143
- Update version in the different components
=> Preparing release v1.41.0

Makefile, hack/install/install-kind.sh, kind-1.19.yaml, kind-1.20.yaml, kind-1.21.yaml, kind-1.22.yaml, kind-1.24.yaml, kind-1.25.yaml, kind-1.26.yaml
- Upgrade KiND version
- Upgrade KiND images
- Add Kubernetes 1.26 testing
=> Upgrade KiND, KiND images and add Kubernetes 1.26

hack/run-e2e-test-suite.sh
=> Upgrade junit cli version

bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
=> Prepare 1.42.0 release

pkg/storage/cassandra_dependencies.go
Signed-off-by: haanhvu <haanh6594@gmail.com>
fixes #659 and #474
=> Support JaegerCommonSpec in JaegerCassandraCreateSchemaSpec

CHANGELOG.md, COMPATIBILITY.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
=> Preparing release v1.43.0

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
- Resolves #2216 2216
- Move jaeger to version 1.45.0 , no changes on the operator.
=> Preparing release v1.45.0

CHANGELOG.md, COMPATIBILITY.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
- Closes https://github.com/jaegertracing/jaeger-operator/issues/2258
-
=> Preparing release v1.47.0

config/manifests/bases/jaeger-operator.clusterserviceversion.yaml
=> olm-upgrade: set correct version

.github/workflows/e2e-elasticsearch.yaml, .github/workflows/e2e-examples.yaml, .github/workflows/e2e-generate.yaml, .github/workflows/e2e-miscellaneous.yaml, .github/workflows/e2e-sidecar.yaml, .github/workflows/e2e-streaming.yaml, .github/workflows/e2e-ui.yaml, .github/workflows/e2e-upgrade.yaml, kind-1.28.yaml
Reverts jaegertracing/jaeger-operator#2299
=> Revert "Test on kubernetes 1.28"

apis/v1/jaeger_types.go, pkg/autodetect/main.go, pkg/autodetect/main_test.go, pkg/autodetect/operatorconfig.go, pkg/cmd/start/main.go, pkg/controller/jaeger/elasticsearch_test.go, pkg/controller/jaeger/jaeger_controller.go
- Continuation of #2278 to fix #1983
- Protect the ESProvisioning setting behind a mutex
=>  Protect the ESProvisioning setting behind a mutex

config/manifests/bases/jaeger-operator.clusterserviceversion.yaml
=> Fix replaces in CSV

Dockerfile
=> Use base image that does not require subscription

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/operator-with-tracing.yaml, versions.txt
=> Prepare release 1.48.1

.github/workflows/e2e-elasticsearch.yaml, .github/workflows/e2e-examples.yaml, .github/workflows/e2e-generate.yaml, .github/workflows/e2e-miscellaneous.yaml, .github/workflows/e2e-sidecar.yaml, .github/workflows/e2e-streaming.yaml, .github/workflows/e2e-ui.yaml, .github/workflows/e2e-upgrade.yaml, kind-1.28.yaml
=> Run e2e tests on Kubernetes 1.28.0

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
Closes https://github.com/jaegertracing/jaeger-operator/issues/2319
- 
- 
=> Prepare release 1.49.0

apis/v1/jaeger_types.go, pkg/autodetect/main.go, pkg/autodetect/main_test.go, pkg/autodetect/operatorconfig.go, pkg/clusterrolebinding/main.go, pkg/clusterrolebinding/main_test.go, pkg/inject/oauth_proxy.go, pkg/inject/oauth_proxy_test.go
=> Protect auth delegator behind a mutex

pkg/util/util.go
=> Fix issue related to new encoding in oauth-proxy image

.github/workflows/base-checks.yaml, .github/workflows/release.yaml, Dockerfile, go.mod, hack/actions/e2e/action.yaml, tests/Dockerfile
=> Bump golang version to 1.21

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
=> Release 1.51.0

go.mod, pkg/controller/jaeger/elasticsearch.go, pkg/controller/jaeger/jaeger_controller.go, pkg/storage/elasticsearch_secrets.go
- 
-  use Go standard errors 
- ci passes
=> use Go standard errors

.github/dependabot.yml, .github/workflows/base-checks.yaml, .github/workflows/codeql.yml, .github/workflows/e2e.yaml, .github/workflows/ossf-scorecard.yml, .github/workflows/publish-images.yaml, .github/workflows/release.yaml, .github/workflows/sdk-scorecard.yaml, Dockerfile, Dockerfile.asserts, README.md, tests/Dockerfile
- fix pin dependencies vulnerabilities from ossf and codeql
- fix codeql and setup ossf scorecard workflow
-  CI
=> fix codeql and setup ossf scorecard workflow

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
-  Preparing release 1.58.0
-  Preparing release 1.58.0
=> Preparing release v1.58.0

CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
=> Preparing release v1.54.0

.github/workflows/release.yaml
=> Fix CI release job name

COMPATIBILITY.md, RELEASE.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
=> Preparing release v1.56.0

CHANGELOG.md, RELEASE.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
-  Prepare 1.57 release
-  Release 1.57
Nothing relevant on the CHANGELOG.md, this is why is empty.
-  Ran e2e
=> Prepare 1.57 release

apis/v1/jaeger_webhook.go, apis/v1/jaeger_webhook_test.go
=> jaeger-agent: reject agent spec

.github/workflows/e2e.yaml, Makefile, kind-1.30.yaml
=> Test on k8s 1.30

CHANGELOG.md, RELEASE.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, versions.txt
- Fixes https://github.com/jaegertracing/jaeger-operator/issues/2700
-  Prepare release 1.62.0
-  Ran e2e tests.
=> Preparing release v1.62.0

.ci/prepare-release.sh, CHANGELOG.md, bundle/manifests/jaeger-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/jaeger-operator.clusterserviceversion.yaml, examples/all-in-one-with-options.yaml, examples/operator-with-tracing.yaml, examples/statefulset-manual-sidecar.yaml, examples/tracegen.yaml, pkg/inject/sidecar.go, tests/cassandra.yml, versions.txt
- https://github.com/jaegertracing/jaeger-operator/issues/2796
- Prepare release with Jaeger 1.65.0, with agent fixed to 1.62.0
- 
- for `jaeger-ui`: `npm run lint` and `npm run test`
=> Prepare release 1.65.0
