- CONTRIBUTING.adoc
Signed-off-by: Georgios Andrianakis <geoand@gmail.com>
> Fix command to deploy the simplest operator

- Makefile
Instead of relying on the binary being present, we just use go run.
We also set all the necessary compilation flags, environment variables
and trap the interrupt signal in order to avoid having Make fail when
the execution of the goal is interrupted
Signed-off-by: Georgios Andrianakis <geoand@gmail.com>
> Fix the run goal

- .travis.yml
- .travis/release.sh
- RELEASE.adoc
> Merge release commit into master

- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/stub/handler.go
This PR moves some of the normalization logic to the stub from the controller. Once the CR is normalized, it's stored back. The side effect is that the controller will only get valid CRs, so that messages related to the normalization will happen only once.
Before this PR:
```
INFO[0005] Storage type wasn't provided for the Jaeger instance 'simplest'. Falling back to 'memory' 
INFO[0005] Created 'simplest'                           
INFO[0005] Created 'simplest'                           
INFO[0005] Created 'simplest'                           
INFO[0005] Created 'simplest'                           
INFO[0005] Created 'simplest'                           
INFO[0005] Created 'simplest'                           
INFO[0005] Storage type wasn't provided for the Jaeger instance 'simplest'. …
```
> Normalize options on the stub and update the normalized CR

- README.adoc
- pkg/cmd/start/main.go
- pkg/controller/production.go
- pkg/controller/production_test.go
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/query.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
- pkg/stub/handler.go
- test/e2e/all_in_one_test.go
- test/e2e/jaeger_test.go
- test/e2e/production_test.go
- test/e2e/sidecar.go
- test/e2e/simplest_test.go
This PR adds support for auto-injection of Jaeger agents into target `Deployment` objects. Technically, this can be done for all objects containing `Pod` objects, like `StatefulSet` or `DaemonSet`, but this PR limits the first implementation to `Deployment`, to get it tested first. If there's demand, it's relatively easy to add support for other constructs.
> Inject sidecar in properly annotated pods

- pkg/deployment/all-in-one.go
- pkg/deployment/all-in-one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
> Fix zipkin port issue

- README.adoc
As we have the badges, the table of contents macro wasn't getting called. One way of fixing this is like this PR. Another way is to get the header + toc as the first things in the doc, with the badges next.
Before:
After:
> Fix table of contents on readme

- pkg/apis/io/v1alpha1/types.go
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all-in-one.go
- pkg/deployment/all-in-one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
Provides a more general way to define annotations, instead of specific approach used in #81.
> Enable annotations to be specified with the deployable components

- CONTRIBUTING.adoc
As requested https://github.com/jaegertracing/jaeger-operator/pull/91#issuecomment-436548822
> Fix operator SDK version as master is too unpredicatable at the moment

- pkg/apis/io/v1alpha1/types.go
- pkg/apis/io/v1alpha1/zz_generated.deepcopy.go
- pkg/deployment/query_test.go
- pkg/util/util.go
> Update generated code and reverted change to 'all-in-one' in CRD

- README.adoc
- pkg/apis/io/v1alpha1/types.go
- pkg/apis/io/v1alpha1/zz_generated.deepcopy.go
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all-in-one.go
- pkg/deployment/all-in-one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
The top level annotations can be overridden by the component level annotations.
> Enable top level annotations to be defined

- .travis/install.sh
- CONTRIBUTING.adoc
- Makefile
Closes #99
When a model has been changed but the deep copy functions haven't been changed, this is shown:
```
$ make ci
Run code-generation for custom resources
Generating deepcopy funcs
Build failed: a model has been changed but the deep copy functions aren't up to date. Run 'make generate' and update your PR.
make: *** [Makefile:27: ensure-generate-is-noop] Error 1
```
Otherwise, this is what a successful build looks like now:
```
$ make ci
Run code-generation for custom resources
Generating deepcopy funcs
Checking...
Formatting code...
Linting...
Building...
Running unit tests...
?   	github.com/jaegertracing/jaeger-operator/cmd	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/apis/io/v1alpha1	0.063s	coverage: 15.5% of statements
? …
```
> Ensure 'make generate' has been executed when model changes are made

- README.adoc
- deploy/examples/openshift/disable-oauth-proxy.yaml
> Fix disable-oauth-proxy example

- deploy/examples/all-in-one-with-options.yaml
- pkg/apis/io/v1alpha1/types.go
- pkg/apis/io/v1alpha1/zz_generated.deepcopy.go
- pkg/ingress/query.go
- pkg/ingress/query_test.go
- test/e2e/all_in_one_test.go
If the query UI base path is defined, then the Ingress needs to also use that path (based on a recent PR in Istio helm chart https://github.com/istio/istio/pull/9588).
Need to consider whether this should also be applied to Route?
> Query base path should be used to configure correct path in ingress

- Makefile
- pkg/deployment/agent.go
> Use proper jaeger-operator version for e2e tests and remove readiness check from DaemonSet

- README.adoc
Change https://github.com/jaegertracing/jaeger-operator/commit/ee056b7e33b6bbd60d1c11261df944bc23b83981 refactored the yaml file in deploy.  This pull request updates the installation instructions in README.adoc to match this refactoring.
> Update README.adoc to match yaml files in deploy

- Gopkg.lock
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- vendor/k8s.io/client-go/testing/actions.go
- vendor/k8s.io/client-go/testing/fake.go
- vendor/k8s.io/client-go/testing/fixture.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
> Add tests for new operator-sdk related code

- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- pkg/strategy/all-in-one.go
- pkg/strategy/all-in-one_test.go
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
- pkg/strategy/production.go
- pkg/strategy/production_test.go
> Rename controller to strategy

- README.adoc
> Add CRD to install steps, and update cleanup instructions

- README.adoc
> Fix crd links

- Makefile
Before:
```
$ make test
Running unit tests...
?   	github.com/jaegertracing/jaeger-operator/cmd	[no test files]
?   	github.com/jaegertracing/jaeger-operator/cmd/manager	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/account	0.051s	coverage: 100.0% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/apis	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/apis/io/v1alpha1	0.033s	coverage: 18.8% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/cmd/start	[no test files]
?   	github.com/jaegertracing/jaeger-operator/pkg/cmd/version	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/config/sampling	0.011s	coverage: 94.1% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/config/ui	0.012s	coverage: 94.1% of …
```
> Silence 'mkdir' from e2e-tests

- Makefile
> Add deploy clean target and rename es/cass to deploy-

- pkg/strategy/all-in-one.go
- pkg/strategy/production.go
> Fix log when spak depenencies are used with unsupported storage

- Gopkg.lock
- pkg/controller/controller.go
- vendor/github.com/openshift/api/route/install.go
Fixes #136 by registering the Route scheme with the SDK Scheme Manager.
> Added Route to SDK Scheme

- pkg/cmd/start/main.go
Helpful for changing the level to `debug` during development.
> Added flag to control the logging level

- README.adoc
- deploy/crds/io_v1alpha1_jaeger_crd.yaml
- deploy/olm-catalog/jaeger-operator.csv.yaml
- deploy/operator-openshift.yaml
- deploy/operator.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
- deploy/service_account.yaml
Resolves #24 
This PR demonstrates how a single operator can be used to create Jaeger instances in different namespaces.
For example,
```
kubectl create -n observability -f deploy/crds/io_v1alpha1_jaeger_crd.yaml
kubectl create -n observability -f deploy/service_account.yaml
kubectl create -n observability -f deploy/role.yaml
kubectl create -n observability -f deploy/role_binding.yaml
kubectl create -n observability -f deploy/operator.yaml
kubectl apply -n other -f deploy/examples/simplest.yaml
```
The problem with this approach is that the `role_binding.yaml` has to have the `namespace` hardcoded. Not sure if this can reference the namespace as a parameter, as with the env vars?
Options:
- leave the current operator deployment focused on a single namespace and provide documentation about …
> Enable single operator to monitor all namespaces

- Makefile
- test/operator.yaml
- test/role.yaml
- test/role_binding.yaml
- test/service_account.yaml
The e2e tests are currently broken in master, due to #188. While we figure out a better way to handle the feature and the tests, this temporary solution should be applied.
Once this PR is applied, the e2e tests are passing again:
```
$ make e2e-tests 
Formatting code...
Building...
Sending build context to Docker daemon  128.8MB
Step 1/4 : FROM alpine:3.8
---> 196d12cf6ab1
Step 2/4 : USER nobody
---> Using cache
---> 18305c5b670d
Step 3/4 : ADD build/_output/bin/jaeger-operator /usr/local/bin/jaeger-operator
---> 74182e60b900
Step 4/4 : ENTRYPOINT ["/usr/local/bin/jaeger-operator"]
---> Running in f1ea53662541
Removing intermediate container f1ea53662541
---> 72d5ace489b1
Successfully built 72d5ace489b1
Successfully tagged jpkroehling/jaeger-operator:latest
Pushing image …
```
> Cloned resources to run the operator on its own namespace for tests

- .gitignore
> Ignore golang coverage html

- pkg/deployment/agent.go
- pkg/ingress/query.go
- pkg/inject/sidecar.go
- pkg/storage/dependency.go
- pkg/storage/types.go
- pkg/strategy/all-in-one.go
- pkg/strategy/controller.go
- pkg/strategy/production.go
- pkg/strategy/streaming.go
Closes #181
Signed-off-by: András Tóth <andras.toth@banzaicloud.com>
> Replaced use of strings.ToLower comparison with EqualFold

- build/Dockerfile
Resolves #219 
```
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-elasticsearch-operator               latest              5698765cb3c2        6 minutes ago       260MB
ploffay/jaeger-operator                               latest              f64e6999bef4        13 minutes ago      266MB
registry.svc.ci.openshift.org/openshift/release       golang-1.10         6cb8ecdeb577        18 hours ago        979MB
registry.svc.ci.openshift.org/openshift/origin-v4.0   base                65b5ece9e8e4        35 hours ago        224MB
centos    
```
Signed-off-by: Pavol Loffay …
> Use centos image

- deploy/examples/simple-prod-deploy-es.yaml
It takes long to deploy 2 nodes.
> Deploy one ES node

- README.adoc
> Add workaround for kubectl logs and get pods commands

- README.adoc
- deploy/examples/business-application-injected-sidecar.yaml
- pkg/controller/deployment/deployment_controller.go
- pkg/inject/sidecar.go
Fixes #60 by removing the namespace constraint when querying for available Jaegers, as Kubernetes will do the right thing and deliver only the ones that the Operator's account can see.
@gregoryfranklin: do you think you'd be able to try this one out?
> Removed constraint on namespace when obtaining available Jaeger instances

- pkg/cronjob/es_index_cleaner.go
- pkg/cronjob/es_index_cleaner_test.go
Resolves https://github.com/jaegertracing/jaeger-operator/issues/196
Related to https://github.com/jaegertracing/jaeger/pull/1318 which has been merged and released as `jaegertracing/jaeger-es-index-cleaner:latest`.  We're just adding some additional environment variables so its also fine to use with older versions of the jaeger-es-index-cleaner image.
> Add storage secrets to es-index-cleaner cronjob

- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch_test.go
https://issues.jboss.org/browse/TRACING-386
> Set shards and replicas based on redundancy policy

- README.adoc
- pkg/apis/addtoscheme_io_v1alpha1.go
- pkg/controller/controller.go
- pkg/controller/jaeger/elasticsearch.go
- pkg/controller/jaeger/elasticsearch_test.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- pkg/inventory/elasticsearch.go
- pkg/inventory/elasticsearch_test.go
- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch/v1alpha1/register.go
- pkg/storage/elasticsearch/v1alpha1/types.go
- pkg/storage/elasticsearch_test.go
- pkg/strategy/production.go
- pkg/strategy/strategy.go
- pkg/strategy/strategy_test.go
Fixes #233 by adding the ES type to the controller's reconcile loop and inventory.
> Fixed deployment of Elasticsearch via its operator

- README.adoc
- pkg/apis/io/v1alpha1/jaeger_types.go
- pkg/cmd/start/main.go
- pkg/controller/jaeger/elasticsearch_test.go
- pkg/controller/jaeger/jaeger_controller.go
- test/e2e/jaeger_test.go
> Automatically detect when the ES operator is available

- pkg/controller/jaeger/elasticsearch.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/storage/elasticsearch.go
- scripts/cert_generation.sh
> Wait for elasticsearch cluster to be up

- .travis/release.sh
- deploy/olm-catalog/jaeger-operator.csv.yaml
- deploy/olm-catalog/jaeger.package.yaml
- deploy/operator.yaml
- test/operator.yaml
Since #173, we have a few more files to bump the version during the releases.
Since #217, we don't have the `operator-openshift.yaml` file anymore, causing the `release.sh` [to fail](https://travis-ci.org/jaegertracing/jaeger-operator/jobs/499756950#L484).
This PR fixes both scenarios and bumps the necessary versions to the latest ones.
> Fixed the bump of release in deploy artifacts

- deploy/role.yaml
- test/role.yaml
Fixes #250 by adding a rule for listing ES clusters. 
> Fixed role rule for Elasticsearch

- pkg/controller/jaeger/jaeger_controller.go
Fixes #231 by comparing the original CR with the post-reconcile state, issuing an update only in case the CR has changed.
> Store back the CR only if it has changed

- pkg/storage/elasticsearch_secrets.go
- pkg/storage/elasticsearch_secrets_test.go
> Remove ES master certs

- README.adoc
- deploy/examples/business-application-injected-sidecar.yaml
- pkg/controller/deployment/deployment_controller.go
- pkg/deployment/all-in-one.go
- pkg/deployment/collector.go
- pkg/deployment/query.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
- pkg/strategy/production.go
- pkg/strategy/production_test.go
- pkg/strategy/streaming.go
- pkg/strategy/streaming_test.go
This PR fixes #244 and applies a small refactoring to the sidecar injection. Special attention to the change to the annotation name, from "inject-jaeger-agent" to "sidecar.jaegertracing.io/inject" (already using a scheme from #201).
> Reinstated sidecar for query, plus small refactoring of sidecar

- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch_test.go
> Use only ES data nodes to calculate shards

- .travis/publish-images.sh
> Added publishing of major.minor image for the operator

- Makefile
Resolves #228 
* It's handly for OCP where the `default` project cannot be used. 
* by default operator should watch all namespaces
> Watch all namespaces in makefile

- test/e2e/daemonset.go
- test/e2e/suite_cassandra_test.go
- test/e2e/suite_elasticsearch_test.go
- test/e2e/utils.go
Resolves #180  Increase the timeout in two places that I've seen cause failures in thethe daemonset test.  Also add waits so that elasticsearch and cassandra tests don't start until es or cassandra are ready.
> Avoid timeouts and race conditions esp. on slow machines

- deploy/examples/all-in-one-with-options.yaml
- jaeger.version
> Bump jaeger version to 1.11

- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
Resolves #298 
The ingress security on OCP was always reverted to "oauth-proxy" if it was configured as "none".
> Fix reverting ingress security to oauth-proxy on openshift if set to none

- pkg/service/collector.go
- pkg/service/collector_test.go
Resolves #305,
Added grpc port into collector service.
> Added grps port into jaeger collector service

- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch_test.go
> Inject archive index configuration for provisioned ES

- pkg/apis/jaegertracing/v1/options.go
- pkg/apis/jaegertracing/v1/options_test.go
> Unmarshall numbers in options to number not float64

- deploy/examples/simple-prod-deploy-es.yaml
> Remove index cleaner from prod-es-deploy example

- README.adoc
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
Resolves #316 
We don't want auto-enabled spark deps for self-provisioned ES
> Disable spark dependencies for self provisioned es

- Makefile
- pkg/controller/jaeger/jaeger_controller.go
- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch_secrets.go
- pkg/storage/elasticsearch_secrets_test.go
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
- pkg/strategy/production.go
- pkg/strategy/production_test.go
- pkg/strategy/streaming_test.go
Resolves #320 
* avoids generating different certs if the operator restarts
* restores edited secrets by user
* stores certs in `/tmp/_cert/namespace/instance_name/uuid`
> Load back Elasticsearch certs from secrets

- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all-in-one.go
- pkg/deployment/all-in-one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
- pkg/inject/oauth-proxy.go
- pkg/inject/oauth-proxy_test.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
> Sorted the container arguments inside deployments

- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
- pkg/storage/elasticsearch.go
- pkg/util/util.go
- pkg/util/util_test.go
> Enabled DNS as the service discovery mechanism for agent => collector communication

- deploy/examples/business-application-injected-sidecar.yaml
- pkg/deployment/agent.go
- pkg/deployment/all-in-one.go
- pkg/deployment/all-in-one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/inject/sidecar.go
- pkg/inventory/service.go
- pkg/inventory/service_test.go
- pkg/service/collector.go
- pkg/service/collector_test.go
- pkg/service/query.go
- pkg/service/query_test.go
> Implemented a second service for the collector

- README.adoc
> Added note about the apiVersion used up to 1.10.0

- test/e2e/all_in_one_test.go
- test/e2e/daemonset.go
- test/e2e/suite_smoke_test.go
- test/e2e/utils.go
Signed-off-by: Kevin Earls <kearls@redhat.com> 
This resolves #326 by adding the ability to find routes with the kubeclient.  
It also contains a minor change to the isOpenShift function, as I realized I did not need to pass it a framework object.
> Update allInOneWithIngressTest to work on OpenShift

- .travis/release.sh
- deploy/olm-catalog/jaeger-operator.csv.yaml
Change provider from `Jaeger` to `CNCF` to enable it to be listed with other CNCF project operators.
@awgreene Would you be able to review and confirm this an appropriate change to update the provider used on operatorhub.io? If so, how does the update get applied to the hub?
> Change Operator provider to CNCF

- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
Adds menu (About sub-menu and Log Out) when OAuth Proxy configured.
Currently when selecting the Log Out button it opens another tab - this may require a change in jaeger-ui.
> Initialise menu to include Log Out option when using OAuth Proxy

- pkg/deployment/agent.go
- pkg/inject/sidecar.go
- pkg/util/util.go
- pkg/util/util_test.go
Was using hardcoded ports, so traffic wasn't getting through to the agent when the ports were changed using the options.
> Derive agent container/host ports from options if specified

- pkg/service/collector.go
Resolves #347 
@jkandasa Haven't been able to reproduce your issue, although it may depend upon the prometheus config being used. I've added an annotation to the headless service which should prevent it being scraped - but if you could verify by testing against the https://hub.docker.com/r/objectiser/jaeger-operator to see if it fixes the problem?
> Add prometheus scrape 'false' annotation to headless collector service

- test/e2e/daemonset.go
- test/e2e/suite_smoke_test.go
This resolves #327 by taking actions that are needed to permit this test to run on OpenShift.  Part of the solution is a bit hacky as it uses os.Exec to call the "oc adm" command, which means the oc client needs to be on the path wherever this test is being run.
It would be preferable to use either the OpenShift Go client of the Rest API to do this, but we don't use those anywhere else in the tests and adding them would be non-trivial.  I will open an issue to do this in the future.
> Update test to run on OpenShift

- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/deployment/agent.go
- pkg/deployment/all-in-one.go
- pkg/deployment/collector.go
- pkg/deployment/ingester.go
- pkg/deployment/query.go
- pkg/util/util.go
- pkg/util/util_test.go
Combining values from the specific component and general details has been done on the following basis:
* Affinity - there is no information about merging the information from two affinity definitions - so seems most appropriate approach is to just allow the more specific component's affinity definition to override any general one
* Tolerations - an array - the `Key` field is not unique, so not possible to select on that basis (as with annotations) - so just aggregate all of the tolerations from the specific component and general definitions.
Resolves #292 
> Add support for affinity and tolerations

- pkg/storage/elasticsearch/v1/types.go
- test/e2e/suite_self_provisioned_elasticsearch_test.go
> Reinstated the registration of ES types

- Makefile
- pkg/account/main.go
- pkg/storage/elasticsearch_secrets.go
> Fail lint goal if not empty

- deploy/olm-catalog/jaeger.clusterserviceversion.yaml
> Update CSV description to comply with guidelines

- Makefile
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/cronjob/es_index_cleaner.go
- pkg/cronjob/es_index_cleaner_test.go
- pkg/strategy/all-in-one_test.go
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
- test/e2e/es_index_cleaner_test.go
Existing test only verifies that the cronjob completes successfully.
This PR extends the test to verify that the job has correctly triggered the es-index-cleaner image and that the task has been performed correctly (i.e. the indices have been removed).
> Enhance ES index cleaner e2e test to verify indices have been removed

- .travis/install.sh
- Makefile
> Reinstate gosec with fix for OOM error

- pkg/cmd/start/main.go
Fixes #383 
Tested on minishift and minikube - to make sure operator deploys ok, but also that the service jaeger-operator is still removed when operator uninstalled.
> Fix rbac policy issue with blockOwnerDeletion

- test/e2e/es_index_cleaner_test.go
- test/e2e/smoketest.go
This fixes #380 where the test would fail if we did the http get before the span got flushed.  I've also removed the hardcoded namespace of "default" from the es_index_cleaner_test.
> Fix race condition in test, remove hard-coded namespace

- README.adoc
- deploy/examples/simple-streaming.yaml
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/strategy/streaming_test.go
The Kafka options were changed in Jaeger 1.11, to use specific properties for consumer and producer sides. The existing shared properties have been deprecated.
With the shared properties, it was possible for have a simplified streaming CR that only defined the kafka properties in storage and/or ingester components - however now the properties are specific to the producer/consumer, they have to be explicitly listed in the relevant component's options.
Unfortunately there is no way to make this backward compatible, as otherwise unexpected properties are passed to the collector. So this will need to be a breaking change - although only affects the streaming stragegy and kafka options.
Tested using [strimzi](https://strimzi.io/). Next step will be to provide some e2e tests for streaming. …
> Change how Kafka is configured for collector and ingester

- test/e2e/all_in_one_test.go
- test/e2e/cassandra.go
- test/e2e/daemonset_test.go
- test/e2e/es_index_cleaner_test.go
- test/e2e/production_test.go
- test/e2e/self_provisioned_elasticsearch.go
- test/e2e/sidecar_test.go
- test/e2e/simplest_test.go
- test/e2e/spark_dependencies_test.go
- test/e2e/utils.go
This fixed #388   Currently if tests fail during the prepare() call ctx.cleanup() will not be called and the namespace created for the test does not get cleaned up.
> Make sure to call ctx.cleanup if prepare() fails

- .travis.yml
- .travis/rune2eTests.sh
- Makefile
- test/e2e/streaming_test.go
- test/e2e/suite_streaming_test.go
- test/e2e/utils.go
- test/kafka-operator.yml
- test/kafka.yml
> Add streaming e2e tests

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Related to #169 
Adds resource requirements to the agent sidecar.
> Add resource requirements to sidecar agent

- test/e2e/smoketest.go
If the smoketest fails it will now return the body of the response so we can see what caused the failure.
> Improve error message when queries fail

- test/e2e/all_in_one_test.go
- test/e2e/cassandra_test.go
- test/e2e/daemonset_test.go
- test/e2e/elasticsearch_test.go
- test/e2e/sidecar_test.go
- test/e2e/spark_dependencies_test.go
- test/e2e/streaming_test.go
If prepare fails verify that the context is not nil before calling cleanup.
> Check that context is not nil before calling cleanup

- pkg/inject/oauth-proxy.go
- pkg/inject/oauth-proxy_test.go
> Add resources requests/limits to oauth_proxy

- deploy/olm-catalog/jaeger.clusterserviceversion.yaml
> Fix csv example and add spec.maturity

- test/kafka.yml
> Use ephemeral storage for Kafka tests

- test/e2e/all_in_one_test.go
- test/e2e/cassandra_test.go
- test/e2e/daemonset_test.go
- test/e2e/elasticsearch_test.go
- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/sidecar_test.go
- test/e2e/streaming_test.go
- test/e2e/utils.go
This fixes #423 We should get t on a per test case basis rather than on a per suite basis.  Otherwise test suites will terminate on the first failure and not run all test cases.
> Correct usage of testing.T

- jaeger.version
- pkg/deployment/agent.go
- pkg/deployment/all-in-one.go
- pkg/deployment/collector.go
- pkg/deployment/ingester.go
- pkg/deployment/query.go
> Update to 1.12 and use new admin ports

- pkg/cmd/start/main.go
> Create metrics service only when running in k8s cluster

- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch_secrets.go
- pkg/storage/elasticsearch_secrets_test.go
- pkg/strategy/controller.go
- pkg/strategy/production.go
- pkg/strategy/production_test.go
> Fix injecting volumes into rollover jobs

- Makefile
> Enable running unit tests in verbose mode for better reporting

- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all-in-one.go
- pkg/deployment/all-in-one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
- pkg/ingress/query.go
- pkg/ingress/query_test.go
- pkg/util/util.go
- pkg/util/util_test.go
> Add label to the common spec

- .travis/rune2eTests.sh
- Makefile
- test/e2e/misc_test.go
- test/e2e/utils.go
This is useful for when we want to validate that we're really testing against the image that we think we're using.
> Log the operator image name when created

- Makefile
- test/e2e/elasticsearch_test.go
- test/e2e/self_provisioned_elasticsearch_test.go
> As of OCP 4.1.2 elasticsearch urls need to be fully qualified

- pkg/config/sampling/sampling.go
- pkg/config/sampling/sampling_test.go
- pkg/config/ui/ui.go
- pkg/config/ui/ui_test.go
- pkg/ingress/query_test.go
- pkg/route/query_test.go
- pkg/service/agent.go
- pkg/service/agent_test.go
- pkg/service/collector.go
- pkg/service/collector_test.go
- pkg/service/query.go
- pkg/service/query_test.go
- pkg/strategy/all-in-one_test.go
- pkg/strategy/production_test.go
- pkg/strategy/streaming_test.go
- pkg/util/dns_name.go
- pkg/util/dns_name_test.go
Closes #466 by making the sanitizing names for services and volumes, to be DNS-compliant. Apart from this change, a name such as `jaegerqe.test` is now possible and yields no errors.
The bigger topic of "validation" in general isn't being touched by this PR. 
cc @jkandasa 
> Sanitize names that must follow DNS naming rules

- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
> Set default redundancy policy to zero

- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/cronjob/es_index_cleaner_test.go
- pkg/cronjob/es_rollover.go
- pkg/cronjob/es_rollover_test.go
- pkg/cronjob/spark_dependencies.go
- pkg/cronjob/spark_dependencies_test.go
- pkg/storage/cassandra_dependencies.go
- pkg/storage/cassandra_dependencies_test.go
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
Fixes #494 by making the property `ttlSecondsAfterFinished` noop. The property still exists in the CRD, as we can't remove due to backwards compatibility reasons, but we are effectively removing the actual feature until we can reliably check which feature gates are on.
> Disable the property ttlSecondsAfterFinished

- RELEASE.adoc
- deploy/examples/all-in-one-with-options.yaml
- jaeger.version
I apparently released the Operator 1.13 while we were still pointing the default underlying image to 1.12. This PR fixes that, making 1.13 the default version for the Operator 1.13.1.
> Bump Jaeger to 1.13

- pkg/cronjob/es_index_cleaner.go
- pkg/cronjob/es_rollover.go
- pkg/cronjob/spark_dependencies.go
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all-in-one.go
- pkg/deployment/all-in-one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
- pkg/storage/cassandra_dependencies.go
- pkg/storage/elasticsearch_dependencies.go
Add annotation to those components that already have similar annotation for Istio
Closes #500
> Add linkerd.io/inject=disabled annotation

- test/e2e/all_in_one_test.go
- test/e2e/cassandra_test.go
- test/e2e/daemonset_test.go
- test/e2e/elasticsearch_test.go
- test/e2e/port_forward.go
- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/sidecar_test.go
- test/e2e/streaming_test.go
- test/e2e/utils.go
In every test where we call CreatePortForward, we are also calling get Pod first.  To simplify this and help shorten tests I've made the following changes:
- Have CreatePortForward call GetPod so the test doesn't have to do it
- If there is a problem in CreatePortForward or GetPod fail the test there rather than returning an error.
> Streamline tests by simplifying calls to CreatePortForward

- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch_test.go
> Make sure the ES operator's UUID is a valid DNS name

- deploy/examples/custom-serviceaccount.yaml
- pkg/account/main.go
- pkg/account/oauth-proxy.go
- pkg/account/oauth_proxy_test.go
Fixes #519 by checking the service account from the JaegerSpec and from JaegerQuerySpec and using it when a value is present.
> Allowed usage of custom SA for OAuth Proxy

- pkg/inventory/account.go
- pkg/inventory/account_test.go
Fixes #521 by not overriding the `Secrets`, `ImagePullSecrets` nor `AutomountServiceAccountToken` fields from service accounts.
> Prevented the Operator from overriding Secrets/ImagePullSecrets on ServiceAccounts

- deploy/crds/jaegertracing_v1_jaeger_crd.yaml
- go.mod
- pkg/apis/jaegertracing/v1/freeform.go
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/cronjob/es_rollover.go
- pkg/cronjob/es_rollover_test.go
- pkg/cronjob/spark_dependencies.go
- pkg/storage/elasticsearch_dependencies.go
- pkg/storage/elasticsearch_dependencies_test.go
- pkg/strategy/all-in-one.go
- pkg/strategy/all-in-one_test.go
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
- pkg/strategy/production.go
- pkg/strategy/streaming.go
- test/e2e/spark_dependencies_test.go
* Added `omitempty` to most properties, as well as the `+optional` tag.
* Renamed a couple of properties, to match their json names. This mismatch is marked as a violation by the openapi code generation (!!).
The code that is generated via `openapi` is not added as part of this PR, because of problems we found during the development of this PR. Once we can get the `openapi` command to generate an acceptable outcome for us, we can run it a first time and add a check to the CI, similar to what we do with `operator-sdk generate k8s`.
> Prepared the code base for openapi code generation

- pkg/apis/jaegertracing/v1/options.go
- pkg/apis/jaegertracing/v1/options_test.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
Fixes Issue #304 
Changed the way that the options is serialized/deserialized, now options does not touch the yaml structure on an update.
This is similar to Freeform type, but it has internally a method for "flat" options, so this support both types of properties, condensed form and normal structure, but not a mix of them.
may be we can/should merge this type with Freeform ?
> Avoid touching the original structure of the options

- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
Related to https://github.com/jaegertracing/jaeger-operator/pull/501#discussion_r304001869
> Use ES single redundancy by default

- Makefile
Related to #481 
Replaces #535 
On the team meeting we agreed to use pinned es-operator version to avoid breaking us.
> Use es-operator from 4.1 branch

- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
ES operator does not allow single redundancy with single ES node.
```
oc logs elasticsearch-operator-5c76fb5664-4wtch -n openshift-logging        10:55 
time="2019-07-18T08:51:44Z" level=info msg="Go Version: go1.10.8"
time="2019-07-18T08:51:44Z" level=info msg="Go OS/Arch: linux/amd64"
time="2019-07-18T08:51:44Z" level=info msg="operator-sdk Version: 0.0.7"
time="2019-07-18T08:51:44Z" level=info msg="Watching logging.openshift.io/v1, Elasticsearch, , 5000000000"
time="2019-07-18T08:52:07Z" level=error msg="error syncing key (myproject/elasticsearch): Failed to reconcile Elasticsearch deployment spec: Wrong RedundancyPolicy selected 'SingleRedundancy'. Choose different RedundancyPolicy or add more nodes with data roles
```
> Use zero redundancy when number of ES nodes is 1

- Makefile
Allow setting the elasticsearch operator image via an environment variable.  This is needed for CI for compatibility testing.
> Allow setting es-operator-image

- pkg/controller/deployment/deployment_controller.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Fixes #443 
I tested and the sidecar was not deleted
I think this is due to the fact that the Kubernetes GC does not delete the sidecar because is part of the pod, also is on the deployment template, which is not a child of the jaeger CR.
This PR implements some logic to "un-inject" the sidecar on the deployment. (but not on existing pods. should we do that??). I used a finalizer here.
@pavolloffay  @jpkrohling  Could you please review? Thank you!!
> Remove sidecar when instance is deleted

- test/e2e/cassandra_test.go
- test/e2e/elasticsearch_test.go
- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/smoketest.go
- test/e2e/streaming_test.go
This simplifies usage of the smoke test by having the smoketest itself handle the port forwarding. This shortens our existing tests, but will also be useful for new tests like ones I will be adding for #144 where I anticipate running the smoke test to validate most of the examplees
> Simplify usage of smoke test by having it do port forwarding

- test/e2e/cassandra_test.go
- test/e2e/elasticsearch_test.go
- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/smoketest.go
- test/e2e/streaming_test.go
This is a follow-up to PR 561.  Once I picked that up and started working on #144 I discovered I could simplify function calls even further, as we were always passing around the same values.
> Further simplify smoke test

- RELEASE.md
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/cmd/start/main.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/upgrade.go
- pkg/controller/jaeger/upgrade_test.go
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all-in-one.go
- pkg/deployment/all-in-one_test.go
- pkg/deployment/args.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
- pkg/storage/cassandra_dependencies.go
- pkg/storage/cassandra_dependencies_test.go
- pkg/strategy/all-in-one_test.go
- pkg/strategy/production_test.go
- pkg/strategy/streaming_test.go
- pkg/upgrade/upgrade.go
- pkg/upgrade/upgrade_test.go
- pkg/upgrade/v1_13_1.go
- pkg/upgrade/versions.go
- pkg/version/main.go
This PR is still in draft mode. The purpose for now is to agree on the main assumptions, like versioning and how to apply the upgrades.
Closes #42
> Added upgrade mechanism for managed Jaeger instances

- Makefile
- deploy/olm-catalog/jaeger.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/apis/jaegertracing/v1/builder.go
- pkg/apis/jaegertracing/v1/const.go
- pkg/cmd/start/main.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- pkg/upgrade/upgrade.go
- pkg/upgrade/upgrade_test.go
- test/operator.yaml
Fixes #567 by setting a `managed-by` value with the `namespace.name` of the operator that manages the instance.
> Changed Operator to set ownership of the instances it manages

- deploy/examples/openshift/custom-sar-oauth-proxy.yaml
- deploy/examples/openshift/with-htpasswd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/inject/oauth-proxy.go
- pkg/inject/oauth-proxy_test.go
Closes #572 by adding a new field to the oauth proxy struct.
> Added htpasswd option to the OpenShift OAuth type

- pkg/apis/jaegertracing/v1/builder.go
- pkg/apis/jaegertracing/v1/const.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- pkg/upgrade/upgrade.go
- pkg/upgrade/upgrade_test.go
Based on the [discussion](https://github.com/jaegertracing/jaeger-operator/pull/571#discussion_r309112130) from #571 and feedback from other sources, I think it's worth having a dedicated label key to indicate which operator is managing the instance, instead of using Kubernetes' `app.kubernetes.io/managed-by`
> Renamed the ManagedBy label to OperatedBy

- pkg/service/agent.go
> Agent service ports with correct protocol

- .travis.yml
- .travis/rune2eTests.sh
- Makefile
- test/e2e/examples_test.go
- test/e2e/utils.go
This is the initial set of tests for #144   It covers everything but:
all-in-one-with-options.yaml
business-application-injected-sidecar.yaml
custom-serviceaccount.yaml
disable-ingress.yaml
openshift/custom-sar-oauth-proxy.yaml
openshift/disable-oauth-proxy.yaml
openshift/with-httpasswd.yaml
> Initial tests for the examples

- pkg/cronjob/es_index_cleaner.go
- pkg/cronjob/es_index_cleaner_test.go
> Configure index cleaner properly when rollover is enabled

- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
@jpkrohling 
After thinking about it, it seems like we don't need the finalizer, the thing with the finalizer is that the finalizer give you access to the jaeger instance before k8 deletes it. here I only need the name at the reconciliation request to do the clean of the sidecars.
Fixes #568
> Get rid of finalizer, clean sidecars when no jaeger instance found

- Makefile
- test/e2e/all_in_one_test.go
- test/e2e/daemonset_test.go
- test/e2e/examples1_test.go
- test/e2e/sidecar_test.go
- test/e2e/smoketest.go
This updates the tests to not install the kafka or es-operators so we can test using operators installed via OperatorHub.  
It also fixes a bug with the use of ES_OPERATOR_NAMESPACE in the Makefile.
> Update tests to permit running with operators installed via OperatorHub

- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/cronjob/spark_dependencies.go
- pkg/cronjob/spark_dependencies_test.go
- pkg/util/util.go
> Add resource limits for spark dependencies cronjob

- Makefile
This is a follow-on to my previous PR.  I realized even if we've installed the kafka-operator via OLD we still need to create the test cluster.
> When using OLM we still need to create and delete the cluster

- test/e2e/examples1_test.go
- test/e2e/examples2_test.go
- test/e2e/streaming_test.go
- test/e2e/utils.go
- test/e2e/wait_util.go
Adding a wait for deployment of the ingester in streaming tests in order to try to eliminate Github build failures.  Also adding some timing on wait steps to try to help with future errors.
> Add wait for ingester to fix streaming test failures

- go.mod
- go.sum
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
> Added default agent tags

- pkg/cronjob/spark_dependencies.go
- pkg/cronjob/spark_dependencies_test.go
So, I store the Elasticsearch credentials in a secret which I then pass in the `storage.secretName` parameter. These credentials are then correctly loaded by the collector, the query and the Elasticsearch cleaner cronjob, but not by Spark dependencies.
I am noob Go programmer so feel free to edit this piece of code as you see fit.
> Load env variables in the given secretName in Spark dependencies

- test/e2e/misc_test.go
- test/e2e/utils.go
Change the tests to use the same EV that the Makefile uses
> Reduce number of EVs needed for CI builds

- .github/workflows/e2e-openshift-4.1.yaml
- Makefile
* Deploy ES 4.2 by default
* Add workflow to test ES operator 4.1
Es operator 4.2 uses operator SDK `v0.7.0`. I think we should keep copied ES CR model files to allows us to update SDK to newer versions e.g. #609 
> Use elasticsearch operator 4.2, add workflow for 4.1

- .ci/install-sdk.sh
- Makefile
> Improved the install-sdk target

- pkg/controller/jaeger/dependencies.go
- pkg/controller/jaeger/deployment.go
- pkg/controller/jaeger/elasticsearch.go
Fixes #670 by making the operator recognize when a resource existed before but ceases to exist while waiting for said resource to become available.
> Recognize when a resource has been deleted while the operator waits

- test/e2e/smoketest.go
This change will give a more specific error message and line number when we fail in this loop.  I've also bumped the timeout, as I don't think we really care about the response time here.
> Improve error messages on test failure

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
As discussed in #28, it was created a way to insert prometheus annotations at agents that are deployed as sidecars so it won't overwrite similar annotations provided by the service.
Closes #28
> Add Prometheus scrape annotations to agent

- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/ingress/query.go
- pkg/ingress/query_test.go
Fixes #85.
I didn't add the auto lookup of an existing secret like `<instance-name>-tls-secret`. This would require the client to be accessible in `ingress/query.go`.
> Add support for TLS on ingress

- deploy/examples/business-application-injected-sidecar.yaml
1. Added the container ports + names, so that 'kubectl expose deployment myapp' creates the appropriate ports
2. Added annotation instructing Istio to inject its sidecar proxy
> Updated the business-application example

- go.sum
- pkg/cronjob/es_index_cleaner.go
- pkg/cronjob/es_index_cleaner_test.go
- pkg/cronjob/spark_dependencies.go
- pkg/cronjob/spark_dependencies_test.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
fixes #697
> add labels to cronjob pod template

- .ci/publish-images.sh
- .github/workflows/publish-images.yaml
The script that is used for this workflow is the same we had before with Travis. It works locally when setting the username/password vars and I did add the same secrets to this repository. I _believe_ this will work, but we'll only know when this gets merged.
Resolves #715
> Added workflows publishing the 'master' container image

- .github/workflows/publish-images.yaml
The publish-images workflow failed with:
```
/home/runner/work/_temp/541137e8-6b47-4ce2-b49f-be1ebfc6e9b1.sh: line 1: ./.ci/publish-images.sh: No such file or directory
```
This is due to the missing `checkout` action, which is included in this PR.
> Added checkout step to publish-images

- pkg/apis/jaegertracing/v1/deployment_strategy.go
- pkg/apis/jaegertracing/v1/deployment_strategy_test.go
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/ingress/query.go
- pkg/ingress/query_test.go
- pkg/strategy/all_in_one.go
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
- pkg/strategy/production.go
- pkg/strategy/production_test.go
- pkg/strategy/strategy.go
- pkg/strategy/streaming.go
- pkg/strategy/streaming_test.go
- test/e2e/all_in_one_test.go
- test/e2e/cassandra_test.go
- test/e2e/daemonset_test.go
- test/e2e/elasticsearch_test.go
- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/sidecar_test.go
- test/e2e/spark_dependencies_test.go
- test/e2e/streaming_test.go
- test/e2e/utils.go
This PR adds a new type, `DeploymentStrategy`, to be used in `JaegerSpec.Strategy` instead of just a `string`. Constants based on the new type are also defined to define valid values.
When merged, this PR will close #137.
> New DeploymentStrategy type for JaegerSpec.Strategy 

- test/e2e/streaming_test.go
While reviewing a PR for @jpkrohling I can across a condition where just waiting for the stateful set wasn't working correctly, so I have added a more precise method.
> Add more definitive wait for kafka clusters

- test/cassandra.yml
- test/elasticsearch.yml
Minikube 1.4 use k8s 1.16 which removes `apps/v1beta1`.
apps/v1beta1 has been promoted to apps/v1 in k8s 1.9  https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md
> Use StatefulSet from apps/v1 API for ES and Cassandra

- test/e2e/misc_test.go
- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/utils.go
A couple of minor fixes here.  First, skip the two test cases that validate that we are using the correct jaeger-operator and elasticsearch-operator images when using OLM, as it's currently a bit difficult or at least cumbersome to know this ahead of time.  Also, while I originally added these as a sanity check, I'm not sure we really need them any longer.
Also, don't call os.Exit() when a test fails and we're in debug mode.  This is not working as I had thought it would, and I need to come up with another approach for this.
> Don't validate images when using OLM

- pkg/deployment/agent.go
- pkg/deployment/all_in_one.go
- pkg/deployment/collector.go
- pkg/deployment/ingester.go
- pkg/deployment/query.go
- Adding liveliness probe #56 
PeriodSeconds: 15
FailureThreshold: 5
I decided for longer liveliness probes, so it would be the last resort if application is not responsive for longer(75s here).
Decision was mostly influenced by similar experiences to what is discussed [here](https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html)
> Add liveliness probe

- .ci/release.sh
- deploy/olm-catalog/jaeger-operator/1.15.1/jaeger-operator.v1.15.1.clusterserviceversion.yaml
With this change, the `containerImage` is still being replaced, while the `replaces` isn't.
> Fixed the release script to only replace the container image on CSV

- .ci/publish-images.sh
Before this PR, the release procedure would publish one image, tagged as `v1.2.3`. After this PR, it publishes two images: `1.2` and `1.2.3`, inline with what we had before moving to GitHub Workflow.
Previously, we had two builds happening for the same commit: one for master, one for the tag. The one for the tag would publish the two images. With GitHub Workflow, only one build is triggered, and `master` is what is detected by the script.
> Fixed the publishing of versioned container images

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
- pkg/service/agent_test.go
This MR should fix the missing `Protocol` properties for three of the created container ports of injected sidecar containers (#771). A test case should cover this - at least for default port numbers. Also, I updated the test case for standalone agent containers to cover the protocols.
> Correctly expose injected UDP container ports

- .ci/script.sh
- Makefile
Since the operator-sdk v0.11.0, we don't need the vendor directory anymore, as `go mod` is used by default.
> Removed vendor step

- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
- pkg/inject/sidecar.go
> Fixed nil pointer when no Jaeger is suitable for sidecar injection

- go.mod
- go.sum
- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
- pkg/cmd/start/bootstrap.go
- pkg/upgrade/upgrade.go
- pkg/upgrade/upgrade_test.go
- pkg/upgrade/v1_15_0_test.go
This might Fix https://github.com/jaegertracing/jaeger-operator/issues/809
Now the errors are gone..
Not sure how bad is to use a "non-cached" client to do the reads, specially on routines that are executed periodically.
@jpkrohling
> Use APIReader for Get/List resources for  autodetect

- deploy/examples/auto-provision-kafka.yaml
Update to reflect snippet used in https://github.com/jaegertracing/documentation/pull/333. Specific images no longer required, and deadlockInterval defaults to 0 now.
> Remove unnecessary options from auto-kafka-prov example

- test/e2e/sidecar_test.go
This should fix a couple of different test failures that occur intermittently with this test.  Previously the vertx app could finish deploying before the Jaeger instance did, and no traces would actually get logged.
> Add wait for jaeger deployment to fix race conditions

- deploy/examples/operator-with-tracing.yaml
- deploy/operator.yaml
- pkg/cmd/start/main.go
> Disabled tracing by default

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
This PR adds a new `JaegerPhase` type, added to the `JaegerStatus`. When running `kubectl get jaegers`, this is what is shown now:
```
$ kubectl get jaegers
NAME                         STATUS    VERSION
jaeger-all-in-one-inmemory   Running   1.15.1
```
When getting the output as YAML for a specific instance, here's the output:
```
$ kubectl get jaegers jaeger-all-in-one-inmemory -o yaml | tail
resources: {}
schedule: '*/30 * * * *'
options: {}
type: memory
strategy: allinone
ui:
options: {}
status:
phase: Running
version: 1.15.1
```
And here's how it shows up in OLM:
Note that the `Version` field isn't being showed in OLM yet.
This is related to #259, although it won't close it, as we might want to keep that open to discuss further status fields in the future.
Signed-off-by: Juraci …
> Added basic status to CR{D}

- test/e2e/streaming_test.go
Merge this once 1.15.0 images are available
> [REQUIRED 1.15.0] revert TLS workaround when 1.15.0 images are available

- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
https://issues.jboss.org/browse/TRACING-824
The currently the default rollover configuration creates:
```
NAME SCHEDULE SUSPEND ACTIVE LAST SCHEDULE AGE
cronjob.batch/simple-prod-es-index-cleaner 55 23 * * * False 0 <none> 2m15s
cronjob.batch/simple-prod-es-lookback */30 * * * * False 0 <none> 2m15s
cronjob.batch/simple-prod-es-rollover */30 * * * * False 0 <none> 2m15s
```
The rollover condition: `'{"max_age": "7d"}'`
This means we run rollover cronjob every 30 minutes and the action takes place every week. Multiple runs a day make might make sense if the conditions are based on the size of the index - however this is supported only in ES6.
We should change the schedule to run once a day. I think it makes the most sense at the moment.
Regarding the default conditions - rollover every 7 …
> Run rollover cronjob by default daily at midnight

- Makefile
> Bump Eleasticserch operator version to 4.3 in deployment scripts

- deploy/examples/with-cassandra.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/storage/cassandra_dependencies.go
- pkg/storage/cassandra_dependencies_test.go
Cassandra pods need sometimes more than 2 minutes to bootstrap. When
this happens, the Cassandra Schema job is failing, and prevents further
deployment of Jaeger components.
By allowing to define a custome timeout for this job, we can circumvent
this problem.
Resolves #818
Signed-off-by: Alexandre Figura <arugifa@users.noreply.github.com>
> Add timeout for Cassandra Schema creation job

- deploy/olm-catalog/jaeger-operator/1.15.1/jaeger-operator.v1.15.1.clusterserviceversion.yaml
- deploy/role.yaml
- pkg/cmd/start/bootstrap.go
- test/role.yaml
This PR fixes the permissions problems related to the creation of `ServiceMonitor` objects. After this PR, this is how a Jaeger Operator bootstrap looks like:
```
$ kubectl logs jaeger-operator-798b484d4b-zssb6 -f
time="2019-12-17T10:05:19Z" level=info msg=Versions arch=amd64 identity=openshift-marketplace.jaeger-operator jaeger=1.15.1 jaeger-operator=v1.15.1-29-g08132f63 operator-sdk=v0.12.0 os=linux version=go1.13.4
time="2019-12-17T10:05:23Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-12-17T10:05:23Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2019-12-17T10:05:23Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2019-12-17T10:05:23Z" level=info msg="The service account …
```
> Fixed permissions for ServiceMonitor objects

- pkg/storage/cassandra_dependencies.go
Resolves #822 
Resolves #469 
Added the missing `KEYSPACE` variable in schema creation
> Configure keyspace in cassandra init job

- Makefile
- pkg/strategy/streaming.go
- pkg/strategy/streaming_test.go
> Fix hardcoded self provisioned kafka broker URL

- Makefile
- pkg/controller/jaeger/jaeger_controller.go
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
- pkg/strategy/production.go
- pkg/strategy/production_test.go
- pkg/strategy/streaming.go
- pkg/strategy/streaming_test.go
- test/e2e/self_provisioned_elasticsearch_kafka_test.go
> Support self provisioned ES in streaming strategy

- test/e2e/elasticsearch_test.go
Signed-off-by: Kevin Earls <kearls@redhat.com>  I've increased the timeout for this cron job as it often takes close to the default 2 minutes, and can sometimes take more than that (at least on OCP 4.1) resulting in test failures.
> Increase timeout to avoid test failures

- test/e2e/wait_util.go
This worked intermittently for cases with > 1 replicas, but not always.
> Pass the correct number of replicas in wait for deployment wrapper

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
In preparation for #848, this would be a good time to remove the `Size` property from the `Collector`, `Ingester` and `Query`. It's been deprecated for quite some time, with a message similar to this:
> The 'size' property for the collector is deprecated. Use 'replicas' instead.
The documentation also shows that `Replicas` should be used:
> Size represents the number of replicas to create for this service. DEPRECATED, use `Replicas` instead.
CRs using `Size` should have been migrated automatically by the operator upon reconciliation, so, existing installations shouldn't break.
> Breaking change - removed 'Size' property from components

- test/e2e/all_in_one_test.go
- test/e2e/daemonset_test.go
- test/e2e/elasticsearch_test.go
- test/e2e/examples1_test.go
- test/e2e/port_forward.go
- test/e2e/smoketest.go
This is based on https://github.com/jaegertracing/jaeger-operator/pull/288 which is out of date.
> Use k8s client random port forward.  Replaces workaround from PR #545

- test/e2e/cassandra_test.go
- test/e2e/spark_dependencies_test.go
- test/e2e/wait_util.go
This is another attempt to fix the failures we've been seeing in CI with cassandra related tests.  I can't guarantee this will work as I've had trouble reproducing it, but these are checks we should be doing anyway, and it will at least give us better information about what is really causing the problem.
The changes are:
1. Add a WaitForStatefulSet to make sure the Cassandra instance is available
2. Add a WaitForJob for the Cassandra schema job
3. Some minor improvements to logging.
> Add waitfors for cassandra instance and schema job

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
> Auto-inject agent tags in multi-container pods

- test/elasticsearch.yml
Old Elasticsearch (5.x) does not on OCP 4.x.
> Use Elasticsearch 6 in tests

- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
In https://github.com/jaegertracing/jaeger-operator/pull/454 we introduced the detection/update of deployments to address https://github.com/jaegertracing/jaeger-operator/issues/442, But after seen this closely, I think this is not the right approach. We should run the scan only at start.
More than that, In my latest tests debugging for fix https://github.com/jaegertracing/jaeger-operator/issues/855.  I see that we don't need to run the scan any more (operator-sdk 0.12.0) , because for some reason (I'm still not sure why) the reconciliation run on each deployment at bootstrap time (see logs). Not sure when this behaviour changed.
[bootstrap-operator.txt](https://github.com/jaegertracing/jaeger-operator/files/4088376/bootstrap-operator.tx …
> Remove deployment updates from autodetect loop

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
> Auto-inject the IP tag for operator-injected agent

- test/e2e/self_provisioned_elasticsearch_kafka_test.go
- test/e2e/streaming_test.go
- test/e2e/utils.go
Delete PVCs at the end of tests which create Kafka instances with persistent storage.   This should not strictly be necessary, as the PVCs should be deleted when the namespace is deleted.  
However, we have had times where a subsequent test gets a panic, particularly because of port-forwarding problems, and then the namespace doesn't get deleted.  This can cause problems with some of our clusters which do not have a lot of resources for volumes.
> Delete PVCs from auto provisioned Jaeger at end of test

- pkg/storage/cassandra_dependencies.go
- pkg/storage/cassandra_dependencies_test.go
This patch is analogous to https://github.com/jaegertracing/jaeger-kubernetes/pull/125.
Background discussion in https://github.com/jaegertracing/jaeger-kubernetes/issues/32.
See comments and commit message.
This is untested so far, waiting for CI run.
> cassandra-create-schema job: set job deadline to 1 day, improve resilience

- pkg/inject/oauth_proxy.go
- pkg/inject/oauth_proxy_test.go
- pkg/inventory/deployment.go
- pkg/util/util.go
- pkg/util/util_test.go
This is another patch for prevent multiple creations of deployments  when a jaeger resource is created.
// cc: @kevinearls 
I only tested with all-in-one strategy, I'll test tomorrow with-cassandra yaml file
> Preserve generated cookie secret on the reconciliation process

- Makefile
- deploy/role.yaml
- pkg/autodetect/main.go
- pkg/controller/deployment/deployment_controller.go
- pkg/controller/jaeger/dependencies.go
- pkg/controller/jaeger/deployment.go
- pkg/controller/jaeger/elasticsearch.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/kafka.go
- pkg/controller/jaeger/kafkauser.go
- pkg/controller/namespace/namespace_controller.go
- pkg/inject/sidecar.go
While debugging a problem with #904, I noticed that the logs are too verbose to be useful. This PR reduces it drastically, by:
* Changing the "waiting for..." messages to be shown only once
* Setting the levels for background process to "trace" for messages that are repeated
* Fixing the role.yaml to include the ability to 'watch' namespaces
Unrelated change included in this PR: the reconciliation for namespaces and deployments had three different contexts each. This PR creates one context and reuses it across the reconciliation. It should make it easier when we decide to instrument those routines.
> Reduced logging verbosity when debug is enabled

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Resolves #900 
Disables agent injection on:
* deployments with label `app=jaeger`
* deployment with the inject annotation value `false`
> Disable agent injection to jaeger instances and when false value is used

- pkg/service/query.go
> Change query service portname to 'http-query'

- pkg/service/collector.go
Also prefix the collector service http ports, as discussed in https://github.com/jaegertracing/jaeger-operator/pull/909#issuecomment-586237703.
> Add http- prefix to collector service port names

- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/utils.go
This is a followup to #904  as a few changes were still required on the testing side.
> Fixes required after update to operator-sdk 0.15.1

- pkg/route/query.go
- pkg/strategy/all_in_one_test.go
- pkg/strategy/production_test.go
- pkg/util/dns_name.go
- pkg/util/dns_name_test.go
- test/e2e/utils.go
Resolves https://issues.redhat.com/browse/TRACING-965
Fixes smoke test failures on OCP `make e2e-tests-smoke` caused probably by https://github.com/jaegertracing/jaeger-operator/pull/891. Other related fixes https://github.com/jaegertracing/jaeger-operator/pull/904 and https://github.com/jaegertracing/jaeger-operator/pull/915
> Fix route name for OCP

- .ci/release.sh
- CONTRIBUTING.md
The `olm-catalog gen-csv` command has been moved as part of Operator SDK 0.15.x.
Reference: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/generating-a-csv.md#generating-a-cluster-service-version-csv-with-operator-sdk
> Fixed the generate CSV command

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Judging from the code, at some point the jaeger-agent accepted metrics scrapes on the other HTTP port (config-rest), but that is no longer the case.  So this change exposes the admin-http port, which does accept metric scrapes.
(It appears that the 1.12.0 release changed this port, see https://github.com/jaegertracing/jaeger/pull/1442 )
I am actually confused as to why any of the other ports are exposed; the idea of the sidecar is that these ports only show up to other containers in the pod on 127.0.0.1 and it would be somewhat harmful if other applications started sending traces to the pod address.  But they're there, so I didn't touch them.
> Sidecar injection: Include the admin-http port

- Makefile
- README.md
- deploy/cluster_role.yaml
- deploy/cluster_role_binding.yaml
- deploy/examples/operator-with-tracing.yaml
- deploy/olm-catalog/csv-config.yaml
- deploy/operator.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
- deploy/service_account.yaml
- pkg/apis/jaegertracing/v1/const.go
- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
- pkg/cmd/start/bootstrap.go
- pkg/controller/deployment/deployment_controller.go
- pkg/controller/jaeger/clusterrolebinding.go
- pkg/controller/jaeger/clusterrolebinding_test.go
- pkg/controller/namespace/namespace_controller.go
- pkg/upgrade/upgrade.go
- pkg/upgrade/upgrade_test.go
- test/e2e/utils.go
- test/service_account.yaml
This is a first draft in getting the operator to work in a single namespace, without cluster roles. This supersedes #830 and fixes #791. It also fixes #905.
This PR also includes instrumentation of the reconciliation for deployments and namespaces, as I added them in order to better understand what needed fixing.
> Changed the operator to gracefully degrade when not on cluster-wide scope

- build/Dockerfile
Resolves #767
- set docker base image to registry.access.redhat.com/ubi8/ubi
> Use ubi as base image

- pkg/controller/deployment/deployment_controller.go
- pkg/controller/jaeger/account.go
- pkg/controller/jaeger/clusterrolebinding.go
- pkg/controller/jaeger/configmap.go
- pkg/controller/jaeger/cronjob.go
- pkg/controller/jaeger/daemonset.go
- pkg/controller/jaeger/deployment.go
- pkg/controller/jaeger/elasticsearch.go
- pkg/controller/jaeger/horizontalpodautoscaler.go
- pkg/controller/jaeger/ingress.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- pkg/controller/jaeger/kafka.go
- pkg/controller/jaeger/kafkauser.go
- pkg/controller/jaeger/route.go
- pkg/controller/jaeger/secret.go
- pkg/controller/jaeger/service.go
- pkg/controller/namespace/namespace_controller.go
Fixes #935 by using an API Reader that bypasses the cache.
> Replaced client.List with reader.List

- deploy/cluster_role.yaml
- deploy/cluster_role_binding.yaml
- deploy/olm-catalog/jaeger-operator/1.17.0/jaeger-operator.v1.17.0.clusterserviceversion.yaml
- test/e2e/utils.go
This PR changes the cluster role to include all the rules from the regular role. Unfortunately, we can't compose roles, as the operator-sdk will *either* bind a service account for the cluster role, *or* to a role. It cannot bind a service account to both a role and a cluster role (!!). 
Related to the finding above, this PR also fixes a problem that went unnoticed with the CSV, which listed a different service account under `clusterPermissions`.
Fixes #931.
> Reorganized cluster roles, added rules to watch all namespaces

- deploy/examples/statefulset-manual-sidecar.yaml
Signed-off-by: Eric Wohltman <eric.wohltman@gmail.com>
This PR is a continuation of https://github.com/jaegertracing/jaeger-operator/pull/946 to add a full StatefulSet example in support of Issue #944.
> Add example StatefulSet with manual sidecar definition

- deploy/examples/tracegen.yaml
fixes #866 
This PR can be merged once the jaeger 1.17 released.
> tracegen uses a versioned image

- Makefile
- test/e2e/examples1_test.go
- test/e2e/utils.go
This should fix #947 by removing an unneeded dependency in the e2e-tests-examples2 target.  It also adds increases some timeouts to avoid some other intermittent failures we've seen, and adds logging to help better diagnose failures.
> Remove unneeded dependency and increase timeout

- pkg/cmd/start/main.go
- pkg/kafka/streaming.go
- pkg/kafka/streaming_test.go
- test/operator.yaml
Closes #957.
This flag is used to tell the operator to provision a smaller Kafka cluster, with 1 replica instead of 3, and with 10Gi instead of 100Gi.
> Added kafka-provisioning-minimal flag

- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
When receiving a reconciliation request, we try to obtain the CR that triggered the event from Kubernetes repository. When using the regular client, we might end up retrieving a cached version that isn't up to date, meaning that we might see errors like the following from time to time:
```
ERRO[0350] failed to store back the current CustomResource  error="Operation cannot be fulfilled on jaegers.jaegertracing.io \"simple-prod\": the object has been modified; please apply your changes to the latest version and try again" execution="2020-03-02 13:55:31.292270472 +0000 UTC" instance=simple-prod namespace=observability
```
This error isn't a big problem, as it will trigger another reconciliation loop and things will eventually stabilize, but given that we might have a couple of reconciliation …
> Use non-cached CR on reconciliation

- pkg/config/tls/tls.go
- pkg/config/tls/tls_test.go
- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
- pkg/deployment/collector_test.go
- pkg/inject/sidecar.go
- pkg/service/collector.go
- pkg/strategy/production.go
Fixes #959 by adding `tls.Update` in the all-in-one strategy as well. As the volume `/etc/config` conflicts with the `ui` configuration, the path has been changed to `/etc/tls-config` as well.
> Added TLS configuration for collector in all-in-one

- test/e2e/utils.go
Five minutes is not needed for timeouts.  If two minutes is not adequate for something we should override the default for that test only.
> Restore two minute timeout

- pkg/autodetect/main.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
- test/e2e/sidecar_test.go
- test/e2e/utils.go
Resolves #899 
In the actual code, when Select is called to select a jaeger instance, it modifies the annotation and set the value to the jaeger instance name.
I think this can lead to the scenario when you rename (or recreate) the Jaeger instance and there is no way to map the old name instance to the new one. I would prefer to preserve the value.
> No modify annotation when injecting

- test/cassandra.yml
- test/e2e/examples1_test.go
This is the first part of fixes for #974   I've seen a number of test failures where the three cassandra replicas either never come up, or they start but shortly thereafter go into an error state. In testing on my laptop changing to 2 replicas has eliminated that problem.
> Only use 2 cassandra replica to avoid CI failures on minikube

- test/e2e/elasticsearch_token_propagation_test.go
- test/e2e/misc_test.go
- test/e2e/utils.go
This is needed to run tests in parallel, as it can return the wrong route if there are multiple jaeger instances with the same name.  (For instance "simple-prod", which is used by multiple tests"
> Verify namespace when finding routes

- test/e2e/streaming_test.go
Make waiting for the kafka instance a little smarter to avoid timeout in internal CI
> Fix wait for kafka instance to avoid race conditions

- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
- pkg/inventory/deployment.go
- pkg/inventory/deployment_test.go
Fixes #963 by using the current `.Spec.Replicas` from the `Deployment` if the desired number of replicas isn't explicitly set.
> Prevent operator from overriding .Spec.Replicas

- test/e2e/smoketest.go
- test/e2e/utils.go
This is needed for the streaming_test/TestStreamingWithTLS test, as that deploys its jaeger instance to the kafka namespace rather than the test specific namespace.
> Pass namespace when searching for insecure endpoint

- .ci/generate.sh
- deploy/crds/jaegertracing.io_jaegers_crd.yaml
Fixes #977 by using `tail` to chop off the first two lines of the CRD file.
> Change 'make generate' to write only a single CRD

- deploy/olm-catalog/jaeger-operator/1.17.1/jaeger-operator.v1.17.1.clusterserviceversion.yaml
For some reason, the generated CSV for 1.17.1 is missing the `displayName`. When installing a bundle from the current master, the operator fails to install because of the missing field.
> Restored the displayName in the CSV

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
When a CR like the following is applied, the current CRD validation will complain that it's invalid:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
name: simplest
spec:
resources:
```
```
The Jaeger "simplest" is invalid: spec.resources: Invalid value: "null": spec.resources in body must be of type object: "null"
```
To keep backwards compatibility, we want to mark a few fields as `nullable`. With this PR, the YAML specified above is accepted.
> Marked specific fields as nullable to keep backwards compatibility

- pkg/controller/deployment/deployment_controller.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
- test/e2e/sidecar_namespace_test.go
> Update deployment sidecar when flags change

- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
> Fix autodetect restarting platform from OpenShift to Kubernetes

- scripts/cert_generation.sh
Upstream script: https://github.com/openshift/cluster-logging-operator/blob/master/scripts/cert_generation.sh
Full history: https://github.com/openshift/cluster-logging-operator/commits/master/scripts/cert_generation.sh
Ported changes
* https://github.com/openshift/cluster-logging-operator/commit/9793597e5c0706cd31c13d4932c01e9ea363c9a4#diff-5a317832296dcbda4dee718589dca819
* https://github.com/openshift/cluster-logging-operator/commit/d639d0cafbf8ef971c6c9d1455eb60e6cab07ec9#diff-5a317832296dcbda4dee718589dca819
* https://github.com/openshift/cluster-logging-operator/commit/43974cdbc949491cfef8d47e027c48b7087860cd#diff-5a317832296dcbda4dee718589dca819
* https://github.com/openshift/cluster-logging-operator/commit/147393748e23723d834a6a00f3f40e12ddba471f#diff-5a317832296dcbda4dee718589dca8 …
> Synch changes in cert generation script with CLO

- .ci/start-minikube.sh
- .github/workflows/e2e-kubernetes.yaml
I have downgraded the CI builds to use Ubuntu version 16.04 instead of 18.04 because of https://github.com/kubernetes/kubernetes/issues/66067.  (Getting minikube to work on 18.04 will require some DNS configuration changes which I don't yet understand.)  
I have also taken this opportunity to update to the most recent version of minikube that I can get to run on Ubuntu 16.04, as we were previously using 1.3.1, which is quite old.
When possible we should got back to using ubuntu-latest and a newer version of minikube.  I have opened issue #1021 to track this.
> Change Ubuntu and Minikube versions to fix CI builds

- test/elasticsearch.yml
This is to avoid test failures when disk usage goes above 95% on the images we are using for tests.
> Disable Elasticsearch feature to monitor available disk space 

- pkg/cronjob/es_index_cleaner.go
- pkg/cronjob/es_index_cleaner_test.go
- pkg/cronjob/es_rollover.go
- pkg/cronjob/es_rollover_test.go
- pkg/cronjob/spark_dependencies.go
- pkg/cronjob/spark_dependencies_test.go
- pkg/storage/elasticsearch_dependencies.go
- pkg/storage/elasticsearch_dependencies_test.go
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
Previously the persisted CR for simplest,yaml included:
```
Es Index Cleaner:
Image:           jaegertracing/jaeger-es-index-cleaner:1.17.1
Number Of Days:  7
Resources:
Schedule:  55 23 * * *
Es Rollover:
Image:  jaegertracing/jaeger-es-rollover:1.17.1
Resources:
Schedule:  0 0 * * *
```
Now
```
Es Index Cleaner:
Number Of Days:  7
Resources:
Schedule:  55 23 * * *
Es Rollover:
Resources:
Schedule:  0 0 * * *
```
> Do not set the default index cleaner, rollover and dependencies image in CR

- pkg/upgrade/v1_18_0.go
- pkg/upgrade/v1_18_0_test.go
- pkg/upgrade/versions.go
> Handle normalization of host:port addresses in operator upgrade for 1.18

- Makefile
The `/deploy/test` dir does not exist in an empty close hence causing failures.
> Configure curl to create dir if does not exists

- deploy/cluster_role.yaml
- deploy/role.yaml
- pkg/autodetect/main.go
- pkg/controller/jaeger/ingress.go
- pkg/controller/jaeger/ingress_test.go
- pkg/ingress/ingress.go
- pkg/ingress/ingress_test.go
- pkg/ingress/query.go
- pkg/inventory/ingress.go
- pkg/inventory/ingress_test.go
- pkg/strategy/strategy.go
- pkg/strategy/strategy_test.go
- test/e2e/wait_util.go
> Migrate Ingress from API extensions/v1beta1 to networking.k8s.io/v1beta1

- .codecov.yml
- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- deploy/examples/simplest.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/config/otelconfig/otelconfig.go
- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
Example CR
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
name: simplest
spec:
allInOne:
image: jaegertracing/opentelemetry-all-in-one:latest
config:
extensions:
health_check:
port: 14269
```
> Add OTEL config to all-in-one

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Comment out volume/mount from sidecar agent until solution is found for https://github.com/jaegertracing/jaeger-operator/issues/1092.
> Comment out volume mount for trusted CA bundle in sidecar agent

- deploy/olm-catalog/jaeger-operator/1.18.1/jaeger-operator.v1.18.1.clusterserviceversion.yaml
Avoids #1085 when opening a PR for the Operator Hub.
> Added missing displayName to CSV 1.18.1

- test/e2e/smoketest.go
```
NAMESPACE=pavolloffay make e2e-tests-self-provisioned-es                                 5:56 
Formatting code...
Building...
Sending build context to Docker daemon  177.8MB
Step 1/7 : FROM registry.access.redhat.com/ubi8/ubi
---> a523835cfc89
Step 2/7 : ENV OPERATOR=/usr/local/bin/jaeger-operator     USER_UID=1001     USER_NAME=jaeger-operator
---> Using cache
---> cdacbb7a92b2
Step 3/7 : RUN INSTALL_PKGS="       openssl       " &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     mkdir /tmp/_working_dir &&     chmod og+w /tmp/_working_dir
---> Using cache
---> b25f1d9d044c
Step 4/7 : COPY scripts/* /scripts/
---> Using cache
---> 399f83a7d70b
Step 5/7 : COPY build/_output/bin/jaeger-operator …
```
> Remove ES error shards toleration from smoke test

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Context: https://github.com/jaegertracing/jaeger-operator/issues/1097
This PR uses any `volumes` or `volumeMounts` under the **agent** node in a Jaeger instance when creating an agent as a sidecar. This still doesn't use the common spec for volumes/mounts, as it seems, *"We don't want to mount all Jaeger internal volumes into user's deployments"*.
However, if someone were to specify a volume/mount under the agent node in the Jaeger instance, they would be mounted to the sidecar, since this would be very intentional.
This seems necessary if one needs to supply files to the agent (e.g. for TLS between the agent and collector with the arg `--reporter.grpc.tls.ca`).
> Mount volumes from agent spec

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/storage/cassandra_dependencies.go
- pkg/storage/cassandra_dependencies_test.go
This adds the `CassandraSchemaSpec.traceTTL` field to allow the user to specify the TTL for their traces.
The TRACE_TTL env var is picked up by this script which creates the schema: https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/schema/create.sh
fixes #1101
> Add TraceTTL to cassandra schema spec

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Fixes #1118 by changing the collector's hostname to connect, and removing the 'service name' flag. With this PR, this is how the logs for the sidecar agent looks like:
```
$ kubectl logs myapp-6f7cc99b66-ckxx9 -c jaeger-agent -f
2020/07/06 13:24:16 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
{"level":"info","ts":1594041857.0278215,"caller":"flags/service.go:116","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1594041857.02812,"caller":"flags/admin.go:120","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1594041857.0281951,"caller":"flags/admin.go:126","msg":"Starting admin HTTP server","http-addr":":14271"}
{"level":"info","ts":1594041857.028216,"caller":"flags/admin.go:112","msg":"Admin server …
```
> Adjusted gRPC options for OpenShift when TLS is enabled

- pkg/service/collector.go
- pkg/service/collector_test.go
Fixes #1117 by setting the gRPC port name to include the `https-` prefix in case TLS is enabled, and `http-` if TLS isn't enabled.
> Set the grpc port name to include http(s) prefix.

- pkg/config/ca/ca.go
- pkg/config/ca/ca_test.go
- pkg/controller/deployment/deployment_controller.go
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all_in_one.go
- pkg/deployment/collector.go
- pkg/deployment/ingester.go
- pkg/deployment/query.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
- pkg/strategy/all_in_one.go
- pkg/strategy/production.go
- pkg/strategy/streaming.go
> Create and mount service CA via ConfigMap

- test/e2e/utils.go
Signed-off-by: Kevin Earls <kearls@redhat.com>  We have recurring problems when testing on OpenShift with failures of tests which use PVCs.  This change will log Warning events when a test fails, and hopefully will help resolve this and other problems.
> Log warning events on failed tests to help debug PVC and other issues

- go.mod
- pkg/cmd/generate/main.go
- pkg/cmd/start/main.go
Fixes #1128 by binding the flags to Viper as part of the command execution, not during the building of the `Command` object.
> Fixed binding of command line flags

- test/e2e/utils.go
Because of the upgrade to operator-sdk 0.18.2 tests started failing when run using an OLM installed Jaeger Operator.  As noted below, if we skip the normal cluster initialization, the namespace for the test doesn't actually get created.
> Update tests to work properly when using OLM installed Jaeger Operator

- test/e2e/utils.go
Add a separate EV to indicate whether the Jaeger Operator has been installed via OLM so we can run tests where the ElasticSearch and Kafka operators have been installed via OLM but the Jaeger Operator has not.
> Add support for JAEGER_OLM EV

- Makefile
- test/e2e/utils.go
SDK_VERSION in Makefile refered to an older version, and the struct
framework.TestCtx is now a deprecated alias for framework.Context.
Updates #1125
> Update downloaded SDK version and update deprecated struct name

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
> Refined Jaeger instance injection logic

- pkg/storage/elasticsearch_dependencies.go
Happen to see the job `jaeger-es-rollover-create-mapping` can't be like other components,`cronjob.batch/jaeger-es-index-cleaner, cronjob.batch/jaeger-es-lookback, cronjob.batch/jaeger-es-rollover` to have Affinity, Tolerations, SecurityContext and ServiceAccountName
> Add common field to  jaeger-es-rollover-create-mapping

- Makefile
- pkg/consolelink/main.go
- pkg/consolelink/main_test.go
- pkg/controller/controller.go
- pkg/controller/jaeger/consolelink.go
- pkg/controller/jaeger/consolelink_test.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- pkg/inventory/consolelink.go
- pkg/inventory/consolelink_test.go
- pkg/strategy/all_in_one.go
- pkg/strategy/all_in_one_test.go
- pkg/strategy/controller_test.go
- pkg/strategy/production.go
- pkg/strategy/production_test.go
- pkg/strategy/strategy.go
- pkg/strategy/strategy_test.go
- pkg/strategy/streaming.go
- pkg/strategy/streaming_test.go
> Add link to openshift console

- go.sum
- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
- pkg/storage/elasticsearch_dependencies.go
Proposed fix for Issue #629. Wrote test to fail where "name", "hello" and "another" custom labels have empty corresponding strings in the selectors, then update selector to use `commonSpec.Labels`, matching the template's labels. Tests pass after change.
Diff also contains a few gofmt and go.sum updates.
> Support custom labels in Jaeger all-in-one deployments (#629)

- Makefile
- deploy/examples/operator-with-tracing.yaml
- deploy/operator.yaml
While testing #1114, I found a small problem in the operator's deployment descriptor, where it's missing one port that is referenced by the service created to back the service monitor.
Also added a target to install the Prometheus Operator.
> Added missing metrics port to operator's deployment

- test/e2e/streaming_test.go
Prior to #1140 we used a single environment variable, OLM, which would tell us whether all three of the Jaeger, ElasticSearch, and Kafka operators had been installed via operator hub.  As of that PR we split functionality into two, with OLM=true now meaning that the ES and Kafka operators had been installed via operator hub, and JAEGER_OLM saying Jaeger had been installed that way.
This test should have been corrected at that time, and should only be run when the Jaeger Operator is installed from operator hub.
> Use the correct OLM flag when determining if test should run

- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
Disabled information about services being injected into pod's environment variables.
This prevents service links environmental variables from conflicting with internal Jaeger environmental variables. 
Image has been verified to work as expected. For verification purposes the image is available at:
fairfaxmedia/jaeger-operator:latest
Thanks to @dackroyd for assistance in these creating this fix.
Fixes #1158 
Relates to jaegertracing/jaeger#1986
> Disabled service links

- pkg/storage/cassandra_dependencies.go
- pkg/storage/cassandra_dependencies_test.go
> Apply the securityContext to the cassandraCreateSchema job

- deploy/examples/statefulset-manual-sidecar.yaml
- deploy/examples/tracegen.yaml
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Tchannel reporter has been removed in 1.18.0
The GRPC reporter was set as default in 1.11.0
This also helps with using OTEL based images since they do not expose `--reporter.type` flag.
> Remove explicitly setting agent's reporter type

- test/e2e/daemonset_test.go
This is a temporary workaround for https://github.com/jaegertracing/jaeger-operator/issues/1175 which depends on this fix: https://github.com/jaegertracing/jaeger/issues/2443 becoming available.
> Temporary workaround for intermittent daemonset test failures

- deploy/cluster_role.yaml
> Add consolelink permissions to cluster role

- README.md
This PR reminds the Kubernetes novice to ensure an ingress-controller is deployed otherwise an ingress address won't be assigned.
Ingress is also deployed in the namespace `observability`, so I've added this in the `kubectl` command.
Please let me know if this is meant to be assumed knowledge and doesn't require explicit documentation. :)
> Add note on ingress-controller and include namespace in README

- pkg/controller/jaeger/jaeger_controller.go
> Create daemonsets after services and deployments.

- .ci/release.sh
Yet another operator-sdk breaking change, apparently. On Operator SDK 0.18.1, a new flag is needed to get the manifests in the older format, which updates the package.yaml. Without this update, CI builds with the operatorhub PRs will fail (see operator-framework/community-operators#2251 and operator-framework/community-operators#2250).
> Make the generate-csv command generate the old-style manifests

- pkg/controller/jaeger/jaeger_controller.go
The https://github.com/jaegertracing/jaeger-operator/pull/1144 added SA to rollover. However the rollover is also used to init storage schema (dependencies) and the service accounts were created after storage dependencies which was causing errors.
> Create service accounts before storage dependencies/init schemas

- Makefile
- test/e2e/autoscale_test.go
- test/e2e/streaming_test.go
- test/e2e/utils.go
This PR adds an autoscaling test for the collector.  For the moment it can only be run on OpenShift.  Future changes will add a test for the ingester, and make it possible to run the tests on Kubernetes.
> Add new autoscale tests

- pkg/controller/namespace/namespace_controller.go
> Remove sidecars of annotated namespaces when annotation is deleted

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Unfortunately, I can't just use the Jaeger CommonSpec's securityContext as that is a `PodSecurityContext` whereas the sidecar can only have a `SecurityContext`. This required me to add an additional config option `containerSecurityContext`. This does add some redundancy as the `Jaeger.Spec.SecurityContext` is not reused.
Is `sidecarContainerSecurityContext` a better name for this config option as the other agent deployments do use the default pod security context?
Resolves #1186
> Added configuration for the agent's securityContext

- .ci/release.sh
- deploy/olm-catalog/jaeger-operator/jaeger-operator.package.yaml
- deploy/olm-catalog/jaeger-operator/manifests/jaeger-operator.clusterserviceversion.yaml
After the release of 1.20, prior to updating the Operator Hub, I noticed that the operator-sdk didn't automatically bump some fields for 1.20.
As a result, I added a few extra sed commands to bump the versions to the release script and ran the commands separately against the existing manifests, making them up to date for 1.20.
> Adjusted OLM manifests for 1.20, adjusted release script

- test/elasticsearch.yml
> expose elasticsearch container ports

- pkg/storage/cassandra_dependencies.go
- pkg/storage/cassandra_dependencies_test.go
Signed-off-by: Ashmita Bohara <ashmita.bohara152@gmail.com>
Since https://github.com/jaegertracing/jaeger/pull/2472 is merged, adding support for custom port here.
Partially Fixes: https://github.com/jaegertracing/jaeger-operator/issues/1179
> Add CQLSH_PORT environment variable

- .ci/publish-images.sh
- .github/workflows/publish-images.yaml
- CONTRIBUTING.md
- Makefile
- build/Dockerfile
I maintained a multi arch images for istio stack https://github.com/querycap/istio
since istio-operator deprecated addonComponents, need jaeger-operator support muti arch.
> Multi arch docker build

- .devbots/needs-triage.yml
- .github/labeler-needs-triage.yaml
- .github/workflows/labeler.yml
The bot that used to add the 'needs-triage' label to new issues stopped working and I can't figure out why. Looks like GitHub has a more official action that does something similar, so, this PR is replacing the 'devbots' with the issue-labeler.
> Replaced devbots with issue-labeler

- .ci/run-e2e-tests.sh
- test/e2e/streaming_test.go
- test/e2e/utils.go
> Add tests for OTEL ingester

- .ci/run-e2e-tests.sh
- test/e2e/elasticsearch_test.go
- test/e2e/self_provisioned_elasticsearch_kafka_test.go
- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/sidecar_namespace_test.go
- test/e2e/sidecar_test.go
- test/e2e/streaming_test.go
- test/e2e/utils.go
This PR reduces the number of OTEL related EVs used by tests to two, and separates their functions.  If SPECIFY_OTEL_IMAGES is true the tests will explicitly add otel image names to CRs.  If SPECIFY_OTEL_CONFIG is true we will remove config values that are not used by the OTEL collector or ingester.
> Simplify OTEL related environment variables

- test/elasticsearch.yml
many container runtimes give SYS_CHROOT by default.  However, CRI-O does not give pods SYS_CHROOT by default.
Instead of relying on the default of a runtime, the pod description should request the capabilities it needs
Signed-off-by: Peter Hunt <pehunt@redhat.com>
> elasticsearch: add SYS_CHROOT capability

- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
> Skip detectClusterRoles for Kubernetes

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/client/versioned/clientset.go
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
Add the `hostNetwork` option to the agent DaemonSet.
Fixes #676.
> Add agent hostNetwork option

- .ci/vgot.sh
- .gitignore
- Makefile
Previous discussions https://github.com/jaegertracing/jaeger-operator/pull/1257
> Fix the dependencies

- .ci/publish-images.sh
- Makefile
- build/Dockerfile
avoid to run `gobuild` with `qemu` to speed up multi arch build.
added `make dockerx` for local run.
> Speed up buildx process

- Makefile
> Publish container - dockerx should not use tag BUILD_IMAGE

- pkg/config/otelconfig/otelconfig.go
- pkg/config/otelconfig/otelconfig_test.go
- pkg/deployment/agent.go
- pkg/deployment/all_in_one.go
- pkg/deployment/collector.go
- pkg/deployment/ingester.go
- pkg/inject/sidecar.go
> Sync OTEL config volume/mount and args

- pkg/upgrade/v1_18_0.go
- pkg/upgrade/v1_18_0_test.go
Fixes #1271.
Previously, the upgrade routine for 1.18 was adding the gRPC host-port option to the CR. In fact, the host-port is already being added by the sidecar/daemonset if this options isn't set. The CR should only be set by users, in which case we wouldn't touch it again (not for sidecar/daemonset, not for upgrades).
> Remove gRPC host-port from being added to the CR (agent)

- .ci/get_test_upgrade_version.sh
- .ci/run-e2e-tests.sh
- .github/workflows/e2e-kubernetes.yaml
- Makefile
- build/Dockerfile
- pkg/controller/jaeger/jaeger_controller.go
- pkg/upgrade/upgrade.go
- test/e2e/upgrade_test.go
Fixes https://github.com/jaegertracing/jaeger-operator/issues/1242
> Update instances status using client.Status().update interface

- pkg/deployment/agent.go
- pkg/deployment/all_in_one.go
- pkg/deployment/collector.go
- pkg/deployment/ingester.go
- pkg/deployment/query.go
- pkg/inject/sidecar.go
- pkg/util/util.go
- pkg/util/util_test.go
> Use New Admin Port Flag

- Makefile
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/jaeger_controller_test.go
- test/e2e/multiple_instances_test.go
- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/utils.go
> Fix secret creation when using self provisioned elasticsearch instances

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
- pkg/strategy/production.go
- pkg/strategy/production_test.go
- pkg/strategy/streaming.go
- pkg/strategy/streaming_test.go
Adds option to set the environment variable JAEGER_DISABLED to query or all-in-one deployment.
Closes: #1148
Signed-off-by: Simon Schneider <github@simon-schneider.eu>
> add env var JAEGER_DISABLED

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- examples/service-types.yaml
- go.sum
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/service/collector.go
- pkg/service/collector_test.go
- test/e2e/examples2_test.go
Adds serviceType option for the collector service.
Closes: #1263
Signed-off-by: Simon Schneider <github@simon-schneider.eu>
> add serviceType for the collector service

- go.mod
- go.sum
Update dependency related to CVE-2019-19794.
> Update github.com/miekg/dns to v1.1.35

- Makefile
- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- go.sum
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch/v1/types.go
> Enable tolerations support in elasticsearch config

- scripts/cert_generation.sh
Force cert regeneration for self prov elasticsearch instances if SAN is invalid
> Regenerate self-provisioned ES TLS cert when it's outdated

- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
Fixes https://github.com/jaegertracing/jaeger-operator/issues/1292
> Update UI documentation link if is present

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
> Copy common spec to avoid touching persisted CR spec

- pkg/controller/deployment/deployment_controller.go
- pkg/controller/deployment/deployment_controller_test.go
Fixes https://github.com/jaegertracing/jaeger-operator/issues/1315
> Trigger deployments reconciliation when jaeger instance is created

- go.mod
- test/e2e/autoscale_test.go
- test/e2e/elasticsearch_index_test.go
- test/e2e/elasticsearch_test.go
- test/e2e/multiple_instances_test.go
- test/e2e/self_provisioned_elasticsearch_test.go
- test/e2e/utils.go
- test/e2e/utils_cr.go
- test/e2e/utils_elasticsearch.go
* Generates spans/services data for 45 days, generates 45 days indices
* runs index cleaner tests with different day limits (`numberOfDays`), 45, 30, 7, 1, 0 days
* Verifies the indices were removed
* Verifies there are no past indices
* Verifies index prefix
* all the tests on production environment
> e2e index cleaner tests improvements 

- Makefile
* RH AMQ operator 1.6 is available now and it is not supporting for Kafka version 2.4
Supported Kafka versions are 2.5 and 2.6
* strimzi-kafka-operator 0.19.0 has 2.5 template.
> Kafka 2.4 not supported by RH AMQ operator 1.6

- test/e2e/elasticsearch_index_test.go
fixes broken es namespace on es index cleaner test on self-provision mode.
@kevinearls can you please review this? Thanks!
> fix e2e tests es index cleaner namespace issue

- go.mod
- go.sum
- pkg/controller/deployment/deployment_controller.go
- pkg/controller/deployment/deployment_controller_test.go
- pkg/inject/sidecar.go
This PR changes the deployment controller so that it always attempt to create the configmaps in the namespace for the target deployments, as long as sidecar injection is desired for the deployment.
> Create missing CA config maps on deployment controller

- pkg/cronjob/spark_dependencies.go
- pkg/cronjob/spark_dependencies_test.go
This fixes #1332   Note however that TLS access for the spark dependencies job is not fully supported (see issue #294 ) in general but will work for the instance described in this issue.
> Add volumes and volume-mounts for spark dependencies

- scripts/cert_generation.sh
> Fix way we force es secret reconcile

- .github/dependabot.yml
- .github/mergify.yml
> Add github actions to dependabot, auto merge on green for dependabot PRs

- .github/mergify.yml
- .github/workflows/base-checks.yaml
- .github/workflows/e2e-kubernetes.yaml
- .github/workflows/publish-images.yaml
Additionally, changed some actions to run only for master or for pull requests for master, avoiding double run for branches pushed to this repository, as it's the case for dependabot PRs.
> Removed the remaining otel items from the mergify configuration

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- examples/collector-with-priority-class.yaml
- examples/query-with-priority-class.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
Note: 
it seems `make generate` introduced some unwanted changes in `deploy/jaegertracing.io_jaegers_crd.yaml`. Not sure whether these changes are required.
> Add ability to indicate PriorityClass for collector and query

- CHANGELOG.md
- RELEASE.md
- pkg/upgrade/utils.go
- pkg/upgrade/v1_22_0.go
- pkg/upgrade/v1_22_0_test.go
- pkg/upgrade/versions.go
- versions.txt
> Preparing release v1.22.0

- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/service/query.go
- pkg/service/query_test.go
This PR should allow users to expose Jaeger's Query service as a NodePort at a specific port. Earlier, the Jaeger Operator did not support specifying a port value and would depend on K8s to randomly select an apt port value. This should resolve this blocker.
Resolves #1307
> Add support for NodePort in Jaeger Query Service

- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/inject/sidecar_test.go
In the agent (`sidecar` mode) we allow user to set their custom TLS configuration, if we detect that the user set the flat `reporter.tls.enable=true`, we skip the automatic configuration.
That logic is not present on the collector, or in the agent in `daemonset` mode.  This PR fixs it. 
Also added a couple of tests.
> Allow configure custom certificates to collector

- CHANGELOG.md
- RELEASE.md
- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- versions.txt
In order to fix https://github.com/jaegertracing/jaeger-operator/issues/1426 I have to do a new release.
We forgot to bump the Jaeger version on `version.txt`
@kevinearls  @jpkrohling Could you please review?
Thanks
> Preparing release v1.22.1

- Makefile
- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- test/e2e/sidecar_namespace_test.go
- test/e2e/sidecar_test.go
ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
It should solve some dns problems, like this https://github.com/jaegertracing/jaeger-operator/issues/676#issuecomment-731601405
> add agent dnsPolicy option

- pkg/upgrade/v1_22_0.go
- pkg/upgrade/v1_22_0_test.go
> Fix override storage and ingress values when upgrade to 1.22

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/cronjob/es_index_cleaner.go
- pkg/cronjob/es_index_cleaner_test.go
- pkg/cronjob/es_rollover.go
- pkg/cronjob/es_rollover_test.go
- pkg/cronjob/spark_dependencies.go
- pkg/cronjob/spark_dependencies_test.go
Resolves #1424 
- Add optional BackoffLimit to JaegerEsIndexCleanerSpec
- Add optional BackoffLimit to JaegerEsIndexCleanerSpec
- Add optional BackoffLimit to JaegerEsRolloverSpec
- Update es_index_cleaner.go CreateEsIndexCleaner function with BackoffLimit
- Update es_rollover rollover function with BackoffLimit
- Update spark_dependencies.go CreateSparkDependencies function with BackoffLimit
- TestEsIndexCleanerBackoffLimit
- TestEsRolloverBackoffLimit
- Add TestSparkDependenciesBackoffLimit
> Implement backoff limit for jobs

- kuttl-test.yaml
- pkg/controller/jaeger/configmap.go
- pkg/ingress/query.go
-  Fixes ingress tests for kuttl
-  The `ingress-nginx`  controller in the `master` branch  has a `ValidatingAdmissionWebhook` for `networking.k8s.io/v1` but the validation aren't migrated yet on ingress controller _0.47.0_ which is the image used by the` deploy.yaml `on `master`  (the validation is already migrated on 1.0.0. See [commit](https://github.com/kubernetes/ingress-nginx/commit/78afe7e389a3b54f5b3b733635c9dc098909ee41#diff-994d32c26c5c0bfa793222a8a5171ed8e4ea78fc850353bb98602b76751f4c2dR47)  ). This produces an error when `jaeger-operator` tried to create an Ingress CR using `networking.k8s.io/v1` API.  It fails with the following message in the log:
`Error: server.go:84] "failed to process webhook request" err="rejecting admission review because the request does not contain an …
>  Fix ingress tests for kuttl 

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/controller/jaeger/configmap.go
- pkg/cronjob/spark_dependencies.go
- pkg/cronjob/spark_dependencies_test.go
- https://github.com/jaegertracing/spark-dependencies allows using variable `ES_TIME_RANGE` to specify how far in the past the job should look to for spans. But that variable is missing in the operator. PR simply adds the possibility to pass the required variable.
- added `elasticsearchTimeRange` configuration option for Jaeger dependencies section
> Allow to pass ES_TIME_RANGE var to Spark dependencies job

- Makefile
* RH AMQ operator `1.7.x` is available now and kafka version `2.5.0` is not supported
* Supported Kafka versions are `2.6.0` and `2.7.0`
* strimzi-kafka-operator `0.20.1` has `2.6.0` template.
```
io.strimzi.operator.cluster.model.InvalidResourceException: Version 2.5.0 is not supported. Supported versions are: 2.6.0, 2.7.0.
```
> kafka 2.5.0 is not supported by RH AMQ operator 1.7.x

- pkg/cmd/start/bootstrap.go
Signed-off-by: Ed Snible <snible@us.ibm.com>
On OIDC-secured clusters, such as IBM Cloud, the `make run` target fails with `FATA[0000] no Auth Provider found for name "oidc"`
This happens when _.kube/config_ contains `users[*].user.auth-provider.config.name` == `oidc`.  When running within the cluster the OIDC provider isn't needed (on my cloud, with my configuration), but when running outside the cluster it is needed -- otherwise the go-client can't talk to the API server.
Include "k8s.io/client-go/plugin/pkg/client/auth/oidc" in binary.  Even though we don't use the include, because it is there [this line](https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/oidc/oidc.go#L50) allows the code to use OIDC if needed.
I did not create a test case because I don't know …
> Include OIDC plugin in binary

- deploy/operator.yaml
Signed-off-by: brunopadz <bpadz@protonmail.com>
- Resolves #1514 
- Adds default resources requests and limits to the Operator container
> Add resources requests and limits to the operator

- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
- pkg/strategy/controller.go
- pkg/strategy/controller_test.go
Signed-off-by: Yuchen Cheng <rudeigerc@gmail.com>
- Resolves #1479 
- Fix overwritten default labels in label selectors of `Service`.
- Remove reserved labels in the normalize operation.
> Fix overwritten default labels in label selectors of `Service`

- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/service/query.go
- pkg/service/query_test.go
- Fixes #1520 
-  Added GRPC port to query service
> Add gRPC port for jaeger-query into its service resource

- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
> Allow TLS flags to be disabled

- Makefile
- deploy/crds/jaegertracing.io_jaegers_crd.yaml
- pkg/apis/jaegertracing/v1/jaeger_types.go
- pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go
- pkg/apis/jaegertracing/v1/zz_generated.openapi.go
- pkg/deployment/all_in_one.go
- pkg/ingress/query.go
- pkg/ingress/query_test.go
-  Fixes https://github.com/jaegertracing/jaeger-operator/issues/1550 
-  Added `ingressClassName` field to the jaeger query ingress spec.
In old version of ingress API this was usually done with annotations (e.g. kubernetes.io/ingress.class). However, with the stable version of ingress API (networking.k8s.io/v1) the annotation way is deprecated and a new field `ingressClassName` is used for this.
> Add ingressClassName field to query ingress

- kuttl-test.yaml
- Fixes ingress kuttl tests
- Instead of use master, I set the version of the nginx ingress controller to 1.0.1, this is due a regression, I filed a issue here: https://github.com/kubernetes/ingress-nginx/issues/7725
> Set version of the nginx ingress controller to 1.0.1

- pkg/controller/deployment/deployment_controller.go
- pkg/controller/deployment/deployment_controller_test.go
- pkg/controller/namespace/namespace_controller.go
- pkg/controller/namespace/namespace_controller_test.go
- Fixes https://github.com/jaegertracing/jaeger-operator/issues/1530
-  There is a warning for query deployment trying to remove his own Sidecar, I don't want to overcomplicated the injection logic, instead I added a logic at the beginning of deployment and on the namespace controller to just ignore the Jaeger deployments. (label` app="jaeger"`). Said that I think this deserve a re-factorization, but for now this PR should fix it.
Hope the use of webhook in v2 will simplify a lot of things here.
> Avoid touching jaeger deps on deployment/ns controller

- pkg/controller/deployment/deployment_controller.go
- pkg/inject/sidecar.go
- pkg/strategy/production.go
- pkg/strategy/production_test.go
This PR allows injecting jaeger-agent sidecar from another Jaeger instance to jaeger-query. 
If the tracing is enabled in jaeger-query deployment the operator adds an annotation `sidecar.jaegertracing.io/inject=<current-jaeger-instance>` to a created common spec object. The annotation is merged with annotations from the CR which allows overriding the instance name e.g.:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
name: jaeger-tenant1
namespace: rhosdt-tenant1
spec:
strategy: production
query:
tracingEnabled: true
annotations:
sidecar.jaegertracing.io/inject: telemeter-jaeger
storage:
type: elasticsearch
options:
es:
max-span-age: 168h # should match numberOfDays*24
esIndexCleaner:
enabled: true
numberOfDays: 7
schedule: "55 23 * * *"
elasticsearch:
nodeCount: 1
````
> Allow sidecar injection for query pod from other Jaeger instances

- .gitignore
- A `kubeconfig` file is created when running the KUTTL E2E tests. Changing the branch is not possible until that file is committed (not desired) or stashed (not desired because we probably want to reuse that `kubeconfig` to test another branch)
> Ignore kubeconfig files

- pkg/inject/sidecar.go
- Resolves #1414
- Resolves #1317 
- When `sidecar.jaegertracing.io/inject` annotation is set to `true` and there are multiple jaeger instances in the cluster, it always chooses the last jaeger instance (from the ordered list of `<namespace>/<jaeger-instance-name>` items). See https://github.com/jaegertracing/jaeger-operator/issues/1414#issuecomment-974802158 for more information.
> Fix finding the correct instance when there are multiple jaeger instances during injecting the sidecar

- config/default/kustomization.yaml
- kuttl-test.yaml
I had to disable metrics by default because if not the users trying to install the operator will be forced to install prometheus operator.
> Disable metrics on generated manifest

- Makefile
- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>
The image pushed to the quay registry is not the same as we generate in the yaml.
https://quay.io/repository/jaegertracing/jaeger-operator?tag=latest&tab=tags
- #1666 
Remove `v` in the kustomization yaml file.
I suppose a new tag should be created to fix this flawed resource file.
> Use image without prefix v

- pkg/cmd/start/bootstrap.go
- During the migration to operator-sdk 1.13 we miss to add some resource schemas. this PR fixes that
- Register openshift , images and console link resources
@rkukura  Could you please review? Thanks!
> Register oschema for openshift resources 

- pkg/util/truncate.go
- pkg/util/truncate_test.go
Resolves: #1677
-  If the excess goes to 0, we continue to add the values to the truncated list to avoid formatting errors
> util.Truncate add the values to the truncated after the excess is 0

- pkg/cmd/start/main.go
- pkg/cronjob/spark_dependencies_test.go
spark-dependencies image is now published to GHCR https://github.com/jaegertracing/spark-dependencies/pkgs/container/spark-dependencies%2Fspark-dependencies.
Before it was published to dockerhub via dockerhub auto-build which is harder to maintain than GHCR integration, therefore switching to GHCR.
> Change spark-dependencies image to GHCR

- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/appsv1/deployment_controller.go
- controllers/appsv1/namespace_controller.go
- controllers/jaegertracing/jaeger_controller.go
> Add leases permissions to manifest.

- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- pkg/cmd/start/main.go
Fixes https://github.com/jaegertracing/jaeger-operator/issues/1697
> Restore default metrics port to avoid breaking helm

- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/jaegertracing/jaeger_controller.go
> Add permissions for imagestreams

- pkg/autodetect/main.go
- pkg/cmd/start/bootstrap.go
- Other initialization routines relies on platform value to do certain detection, in this particular case the oauth image was not detected correctly.
- We need to make sure to detect the platform before doing any other initialization. In order to do that I made the first call of auto-detect synchronous (other calls will happens as usual, each 5 sec) . I think we should not have problems with this, but if this is a problem we can at least change the platform detection to be sync on the first call.
> First call of autodetect should be synchronous

- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
- This PR should fixes [Issue-1684](https://github.com/jaegertracing/jaeger-operator/issues/1684) or at least alleviate the problem, The message of _"Waited for Xs due to client-side throttling, not priority and fairness"_ is caused because a lot of API calls to K8s. It seems like calling  `PreferedServerResources` does a lot of calls to the API when the cluster has a lot of different resource Kinds.
- To avoid this, in this PR we ask for `ServerGroups`  and then only get the resources for our interested Groups.
Note: I still see one line in the log with the error "Waited Xs.." but one single time, I don't see the same error repeating in logs each N seconds. so I think this can be considered a fix.
> Avoid calling k8s api for each resource kind on the cluster

- pkg/route/query.go
- pkg/route/query_test.go
- pkg/service/query.go
- Eliminates warnings logged every 5 seconds due to OpenShift's router attempting to perform health checks on the query-grpc port.
- Include spec.port.targetPort selecting the query-http[s] port in the OpenShift route.
> Only expose the query-http[s] port in the OpenShift route

- tests/cmd-utils/wait-cronjob/main.go
-#1729
- Fix some issues in the logging
- Avoid stopping the program when the cronjob is not found
- Increase the default timeout of the program to ensure it is bigger than the timeout set by KUTTL
> #1729: improve robustness of wait-cronjob

- .ci/vgot.sh
> get rid of deprication warning when installing dependencies

- pkg/metrics/instances.go
- pkg/metrics/instances_test.go
- Added metric that determines the amount of CRs using autoprovisioned Elasticsearch storage.
> Add ES autoprovisioning CR metric

- apis/v1/options.go
- apis/v1/options_test.go
Closes #1733 
- option fields not of type string, [make the operator panic](https://github.com/jaegertracing/jaeger-operator/issues/1649#issuecomment-1001271023). 
- Check type before making a type association in `(*Options).UnmarshalJSON` method.
- Return error if the elements of the argument list are not of type `string`.
- If `Options` cant be decoded [error 400](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/admission/http_test.go#L78) is returned.
```bash
controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-jaegertracing-io-v1-jaeger", "UID": "6c77a050-a28d-4172-abc4-56f61670baef", "kind": "jaegertracing.io/v1, Kind=Jaeger", "resource": …
```
> fix panic caused by an invalid type assertion

- CONTRIBUTING.md
- Resolves #1758
- Corrections for out of date text
> Fix contributing docs

- CONTRIBUTING.md
- documentation link works again
- link adaption
> fix olm-csv link in contributing description

- .github/workflows/base-checks.yaml
- .github/workflows/release.yaml
- .github/workflows/sdk-scorecard.yaml
- Makefile
- Make sure we always use the correct version of the operator-sdk in builds. Suggested in chat by @pavolloffay 
- - Added a Makefile target to install the operator-sdk, mostly copied from Pavol's [equivalent change](https://github.com/open-telemetry/opentelemetry-operator/pull/728) to the open-telemetry collector:
> Make sure that we always use the correct operator-sdk version

- apis/v1/jaeger_types.go
- apis/v1/jaeger_webhook.go
- apis/v1/jaeger_webhook_test.go
- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/elasticsearch/elasticsearch_controller.go
- pkg/autodetect/main.go
- pkg/cmd/start/bootstrap.go
- pkg/controller/elasticsearch/elasticsearch_controller.go
- pkg/controller/elasticsearch/elasticsearch_controller_test.go
- pkg/metrics/instances.go
- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch_test.go
- pkg/strategy/controller.go
- pkg/strategy/production.go
- pkg/strategy/streaming.go
- pkg/upgrade/v1_31_0.go
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
Resolves #1720 
Notable changes:
* defaulting webhook - set ES number of nodes from the referenced ES instance
* validating webhook - validate if references ES instance exists
* ES controller - watch for changes and update ES nodes in Jaeger CR accordingly.
Test data:
```
kubectl apply -f - <<EOF
apiVersion: logging.openshift.io/v1
kind: Elasticsearch
metadata:
annotations:
logging.openshift.io/elasticsearch-cert-management: "true"
logging.openshift.io/elasticsearch-cert.jaeger-shared-es: user.jaeger
name: shared-es
spec:
managementState: Managed
nodeSpec:
resources:
limits:
memory: 1Gi
requests:
cpu: 200m
memory: 1Gi
nodes:
- nodeCount: 1
proxyResources: {}
resources: {}
roles:
- master
- client
- data
storage: {}
redundancyPolicy: …
```
> Automatically set num shards and replicas from referenced OCP ES

- .github/workflows/base-checks.yaml
- .github/workflows/codeql.yml
- .github/workflows/e2e-allinone.yaml
- .github/workflows/e2e-cassandra.yaml
- .github/workflows/e2e-elasticsearch.yaml
- .github/workflows/e2e-examples.yaml
- .github/workflows/e2e-generate.yaml
- .github/workflows/e2e-istio.yaml
- .github/workflows/e2e-outside-cluster.yaml
- .github/workflows/e2e-smoke.yaml
- .github/workflows/e2e-streaming.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/publish-images.yaml
- .github/workflows/sdk-scorecard.yaml
- #1791
- Use [the paths-ignore GitHub Actions Workflow](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) feature to save resources when the changes are done just in Markdown files.
> Skip running the CI for changes in documentation #1791

- .github/dependabot.yml
- Currently dependabot jobs can run at any time of day, and as a result sometimes clog up the build queue.  This change should restrict them to running after 3:00AM CET, or after 9:00PM eastern time in the US.
- Add a time and timezone to the dependabot config file
> Schedule dependabot jobs to run after 3:00 AM CET

- Makefile
- `make undeploy` & `make uninstall` work as expected.
- `make undeploy` will result in `build config/default | kubectl delete --ignore-not-found=false -f -`
- `make undeploy ignore-not-found=true` will result in `build config/default | kubectl delete --ignore-not-found=true -f -`
```
kubectl delete -h 2&>1 | grep ignore-not-found 
--ignore-not-found=false: Treat "resource not found" as a successful delete. Defaults to "true" when --all is specified.
```
---
cc @kevinearls
> fix: make uninstall and undeploy

- Makefile
- hack/install/install-controller-gen.sh
- hack/install/install-utils.sh
- #1814
- Change the way to install `controller-gen` to use the mechanisms from the `hack/install` folder
> Install controller-gen only when it is needed

- bundle/manifests/jaeger-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/jaeger-operator-metrics_v1_service.yaml
- bundle/manifests/jaeger-operator-webhook-service_v1_service.yaml
- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- bundle/manifests/jaegertracing.io_jaegers.yaml
- bundle/manifests/prometheus_rbac.authorization.k8s.io_v1_role.yaml
- bundle/manifests/prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- config/default/kustomization.yaml
- config/webhook/deployment_inject_patch.yaml
- config/webhook/kustomization.yaml
- config/webhook/manifests.yaml
- controllers/appsv1/deployment_webhook.go
- tests/e2e/sidecar/render.sh
- tests/e2e/sidecar/sidecar-skip-webhook/00-assert.yaml
- tests/e2e/sidecar/sidecar-skip-webhook/00-install.yaml
- tests/e2e/sidecar/sidecar-skip-webhook/01-assert.yaml
- tests/e2e/sidecar/sidecar-skip-webhook/01-errors.yaml
- tests/e2e/sidecar/sidecar-skip-webhook/01-install.yaml
- tests/e2e/sidecar/sidecar-skip-webhook/annotate-ns.sh
- fixes #1844
- change deployment webhook [failurePolicy](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy) to ignore.
- add common label [name](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels)
- patch webhook to ignore deployments with label `app.kubernetes.io/name: jaeger-operator`
- add e2e test to verify the patch works as expected.
---
cc @esnible
> Fix: webhook deadlock 

- pkg/service/agent.go
- pkg/service/collector.go
Signed-off-by: Karol Szwaj <karol.szwaj@gmail.com>
- https://github.com/jaegertracing/helm-charts/issues/344#issuecomment-1100166786 (partially)
Adding a prefix to service port names, resolves issues with istioctl 
```bash
Info [IST0118] (Service tracing-jaeger-agent.kyma-system) Port name config-rest (port: 5778, targetPort: 5778) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service tracing-jaeger-collector-headless.kyma-system) Port name c-tchan-trft (port: 14267, targetPort: 14267) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service tracing-jaeger-collector.kyma-system) Port name c-tchan-trft (port: 14267, targetPort: 14267) doesn't follow the naming convention of Istio port.
```
Potentially possible problems similar to this old …
> Add http- prefix to port names in collector and agent services

- controllers/appsv1/deployment_webhook_test.go
- pkg/autodetect/main_test.go
- pkg/controller/jaeger/jaeger_controller_test.go
- pkg/controller/namespace/namespace_controller_test.go
- pkg/metrics/instances_test.go
- pkg/upgrade/upgrade_test.go
- pkg/upgrade/v1_15_0_test.go
- pkg/upgrade/v1_17_0_test.go
- pkg/upgrade/v1_18_0_test.go
- pkg/upgrade/v1_20_0_test.go
- pkg/upgrade/v1_22_0_test.go
- Fixes #1854 
- This PR replaces calls to the deprecated NewFakeClient() function (from igs.k8s.io/controller-runtime/pkg/client/fake) with NewClientBuilder()
> Replace instances of deprecated NewFakeClient function

- apis/v1/jaeger_webhook.go
- apis/v1/jaeger_webhook_test.go
- apis/v1/options.go
- From the upcoming version 1.34 the tls enabled flag is required when using tls options. https://github.com/jaegertracing/jaeger/pull/3030 
- to avoid breaking existing setups, tls flags are extended by the missing enable flag if necessary.
---
cc @rubenvp8510 @pavolloffay
> adapt tls flag usage for upcoming release

- CHANGELOG.md
- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/jaeger-operator.clusterserviceversion.yaml
- versions.txt
blocked by https://github.com/jaegertracing/jaeger-operator/issues/1702, https://github.com/jaegertracing/jaeger-operator/pull/1891
Closes https://github.com/jaegertracing/jaeger-operator/issues/1879
> Preparing release v1.34.0

- bundle/manifests/jaeger-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/jaeger-operator-metrics_v1_service.yaml
- bundle/manifests/jaeger-operator-webhook-service_v1_service.yaml
- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- bundle/manifests/jaegertracing.io_jaegers.yaml
- bundle/manifests/prometheus_rbac.authorization.k8s.io_v1_role.yaml
- bundle/manifests/prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- config/default/kustomization.yaml
- config/webhook/deployment_inject_patch.yaml
- closes https://github.com/jaegertracing/jaeger-operator/issues/1870
- remove previously introduced common label
- use `name=jaeger-operator` to bypass the jaeger deployment webhook
---
cc @rubenvp8510
> fix: remove common name label

- pkg/cronjob/es_rollover.go
- pkg/cronjob/es_rollover_test.go
- Prevent write to dependency store on openshift platform. (currently this does not work because permissions are limited)
- When using openshift, the dependency index rollover is disabled. 
---
cc @rubenvp8510
> fix: skip dependencies on openshift platform

- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch_secrets.go
- pkg/storage/elasticsearch_test.go
- Closes https://github.com/jaegertracing/jaeger-operator/issues/1932
- Introduce temporary environment variable `JAEGER_OPERATOR_GRANULATED_SG` that is used to grant `sg_role_curator` permission only to `es-rollover` jobs. Requieres https://github.com/jaegertracing/jaeger/commit/3499c88f640e8d9c54cde37c7b0de32c98bc80e5 since writing to the dependency store needs to be disabled.
- By default use [sg_role_curator](https://github.com/openshift/origin-aggregated-logging/blob/11a17d44877e178ac8dc6aefd6dda6c8dba5888e/elasticsearch/sgconfig/roles.yml#L65) instead of [sg_role_jaeger](https://github.com/openshift/origin-aggregated-logging/blob/11a17d44877e178ac8dc6aefd6dda6c8dba5888e/elasticsearch/sgconfig/roles.yml#L86)
alternative to https://github.com/jaegertracing/jaeger-operator/pull/1933
> Fix/ocp es rollover #1932

- pkg/cmd/start/main.go
- Closes https://github.com/jaegertracing/jaeger-operator/issues/1952
- change default settings of `openshift-oauth-proxy-image` from `openshift/oauth-proxy:latest` to `quay.io/openshift/origin-oauth-proxy:latest`.
Do we want to keep the `latest` tag? For rollover etc. we also use `latest`. But this brings the risk that faulty external updates could break the operator functionality.
```
REPOSITORY                                                                     TAG                   IMAGE ID       CREATED        SIZE
quay.io/openshift/origin-oauth-proxy                                           latest                0b2b08dd4482   3 weeks ago    299MB
openshift/oauth-proxy …
```
> fix: point to a newer openshift oauth image 4.12

- tests/e2e/elasticsearch/es-from-aio-to-production/README.md
- tests/e2e/elasticsearch/render.sh
- Part of solving #276
- Add an E2E test to check there are not issues when a Jaeger instance deployed using `allInOne` strategy is upgraded to use `production` deployment strategy.
> Add E2E test to test upgrading from an allinone Jaeger Instance to production

- tests/e2e/miscellaneous/collector-autoscale/03-assert.yaml
- tests/e2e/miscellaneous/render.sh
- tests/e2e/render-utils.sh
- tests/e2e/streaming/render.sh
- tests/e2e/streaming/streaming-with-autoprovisioning-autoscale/07-assert.yaml
- Make the auto-scale E2E tests more robust
- Decrease the number of max replicas. Usually, the replicas are 5 (the maximum) but others, the collector doesn't scale enough because the load is not enough. But increasing the load can be a problem because the resource limits in the CI environment. Decreasing the number of max replicas to 3 ensures the scale is tested properly while the load for the cluster is not too high
- Fix the assert for the auto-scale in the `streaming/streaming-with-autoprovisioning-autoscale` E2E test
- Remove the `replicas` parameter from the `render_install_tracegen` macro because it was not really used
> Change the parameters for the auto-scale E2E test to help it to be more robust

- Makefile
- hack/enable-operator-features.sh
- hack/run-e2e-test-suite.sh
- Add a way to set the `LOG-LEVEL` and `KAFKA-PROVISIONING-MINIMAL` when doing `make deploy`
This will help the autoprovisioned Kafka E2E tests in environments with low resources like CI or a local machine.
This will probably fix #1990
> Allow setting the log level and minimal Kafka deployment

- Dockerfile
- Makefile
Sometimes, the Golang dependencies download fails during the build of the Jaeger Operator or the Jaeger Operator container image. These errors are usually caused due to network errors.
This PR adds a retry mechanism to avoid this issue.
> Increase robustness of go dependencies download

- tests/build-utils/build-assert-e2e-img.sh
- tests/build-utils/get-assert-e2e-img.sh
- tests/e2e/Makefile
Sometimes, this error appears ([full log](https://github.com/jaegertracing/jaeger-operator/runs/7411403010?check_suite_focus=true)):
```sh
Loading the quay.io/runner/asserts-e2e:1658241386 container image in the KIND cluster
ERROR: image: "quay.io/runner/asserts-e2e:1658241386" not present locally
```
In this case, the built image is `quay.io/runner/asserts-e2e:1658241385`. This error is not easy to reproduce. It happens because the `ASSERT_IMG` make variable depends on the timestamp:
```make
export ASSERT_IMG ?= ${IMG_PREFIX}/asserts-e2e:$(shell date +%s)
```
Sometimes, it is reevaluated in the `build-assert-job` make target:
```make
$(VECHO)docker build -t $(ASSERT_IMG)  -f Dockerfile.asserts . $(DOCKER_BUILD_OPTIONS)
$(VECHO)echo …
```
> Avoid reevaluation of the ASSERT_IMG Make variable

- tests/e2e/elasticsearch/render.sh
- tests/e2e/render-utils.sh
- Some E2E tests from the `elasticsearch` test suite are no supported for Elasticsearch OpenShift Operator versions older than 5.4. This PR skips them
- Add the `get_elasticsearch_openshift_operator_version` to get the Elasticsearch OpenShift Operator
- Skip unsupported tests based on Elasticsearch OpenShift Operator version
> Skip E2E tests when the feature is not supported by the Elasticsearch OpenShift Operator

- tests/cmd-utils/get-token.sh
- tests/e2e/ui/render.sh
Avoid race conditions when `get-token.sh` is called, waiting for the deployments to be done again.
If a Jaeger instance is modified and the pods are not started again fast enough, the smoke tests can fail. With this change, we wait until everything is there again before creating the smoke test jobs.
> Wait until the deployments are there again in get-token.sh

- Makefile
- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- Upgrade the operator-sdk from 1.22.0 to 1.22.2
> Upgrade operator-sdk to 1.22.2

- tests/cmd-utils/get-token.sh
- tests/templates/openshift/find-service.yaml.template
- tests/templates/openshift/otlp-smoke-test.yaml.template
- tests/templates/openshift/report-spans.yaml.template
- tests/templates/openshift/sa-secret.yaml.template
- tests/templates/openshift/smoke-test.yaml.template
- Fix E2E smoke tests for OCP 4.11
Starting on Kubernetes 1.24, when creating a Service Account, no tokens are created associated to it. You need to create one and associate to the desired Service Account.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md
This PR follows that process in order to allow the smoke tests to get the info from the Jaeger REST API.
Note this change is backward compatible with older OCP versions.
> Fix e2e secret for newer OCP versions

- apis/v1/jaeger_types.go
- apis/v1/zz_generated.deepcopy.go
- bundle/manifests/jaegertracing.io_jaegers.yaml
- config/crd/bases/jaegertracing.io_jaegers.yaml
- docs/api.md
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
- pkg/util/util.go
Signed-off-by: Micah Nagel <micah.nagel@parsons.com>
Resolves https://github.com/jaegertracing/jaeger-operator/issues/2032
- Adds support for `containerSecurityContext` in common spec
- `containerSecurityContext` used as the security context for containers in each of agent, all-in-one, collector, ingester, query
> Add container security context support

- hack/install/install-golangci-lint.sh
- Bump `golangci-lint` version from `1.48.0` to `1.49.0`
> Bump golangci-lint version from 1.48.0 to 1.49.0

- apis/v1/jaeger_types.go
- bundle/manifests/jaegertracing.io_jaegers.yaml
- config/crd/bases/jaegertracing.io_jaegers.yaml
- docs/api.md
- examples/ingress-with-host-pathType.yaml
- pkg/ingress/query.go
- pkg/ingress/query_test.go
- Resolve https://github.com/jaegertracing/jaeger-operator/issues/2065
- Added `pathType` to `ingress`
> feat: added pathType to ingress

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Signed-off-by: Jacob Colvin <jacobcolvin1@gmail.com>
Fixes #1202
This PR is mainly just taking code from #1230 which was unfortunately abandoned.
I believe I've fixed all of the issues with #1230, which involved:
- Changing `Handler` to `ProbeHandler`.
- Skipping checks for conflicting ports on the agent container. (Without this, it seems that probes could not be added if a deployment was restarted/upgraded, because the port was already used on the deployment from the last injection.)
> Add liveness and readiness probes to injected sidecar

- tests/e2e/elasticsearch/Makefile
- tests/e2e/examples/Makefile
- tests/e2e/render-utils.sh
- tests/e2e/streaming/Makefile
- tests/templates/assert-kafka-cluster.yaml.template
- tests/templates/assert-zookeeper-cluster.yaml.template
- Newer Kafka Operator versions deploy `StrimziPodSet` instead of `StatefulSet`. This can be a problem if we want to do something with an older version of the Kafka Operator
> Fix Kafka tests for old Kafka operator version

- go.mod
- go.sum
Which problem is this PR solving?
Upgrades the net and sys dependencies to mitigate [CVE-2022-27664](https://avd.aquasec.com/nvd/2022/cve-2022-27664/)
Latest version was failing image scans.
Before changes:
```
$ trivy i quay.io/albert.lockett2/jaeger-operator:1.38.0
....
jaeger-operator (gobinary)
==========================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+------------------+------------------+----------+------------------------------------+-----------------------------------+---------------------------------------+
|     LIBRARY      | VULNERABILITY ID | SEVERITY |         INSTALLED VERSION          |           FIXED VERSION           |                 TITLE                 |
+------------------+------------------+----------+-------------------------------- …
```
> [Bug]: CVE-2022-27664

- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/manifests/bases/jaeger-operator.clusterserviceversion.yaml
- olm upgrades do not work
- `Error: Cycle detected, jaeger-operator.v1.38.1 replaces jaeger-operator.v1.38.1`
- change version number in manifests
---
cc @iblancasa
> fix: release replacement

- pkg/service/collector.go
- pkg/service/collector_test.go
- tests/e2e/miscellaneous/istio/03-assert.yaml
This pr changes the service port naming to avoid TLS termination issues when using istio. Istio recognizes which application protocol is used by the port name. Our last name change of the service port name from `https-grpc` to `grcp-https` has resulted in TLS traffic being treated like unencrypted traffic.
Resulting in a handshake error: `authentication handshake failed: tls: first record does not look like a TLS handshake`.
In the analysis, the port names confused me several times. Since I didn't want to just switch grpc and https again, I tried to make the names a bit more descriptive. Note the application protocol is determined by the port name prefix: `<protocol>[-<suffix>]`.
- `grpc-https` (invalid) -> `https-grpc` (valid) -> `https-model-proto` (valid) -> `tls-grpc-jaeger` (valid)
- …
> Fix: svc port doesnt match istio convention

- pkg/cmd/start/bootstrap.go
- pkg/cmd/start/main.go
Fix #2118
Adding min tls version for webhook server during bootstraping
> fix for min tls version to v1.2

- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
The liveness probes added in https://github.com/jaegertracing/jaeger-operator/pull/1605 are not working for the ingester and query, because of a copy / paste mistake (sorry for that 😞).
This PR fixes the liveness probe configuration for the ingester and query.
> Fix Liveness Probe for Ingester and Query

- pkg/ingress/query.go
- pkg/ingress/query_test.go
This resolves #2088 If a base path is set in the CR and the streaming strategy is being used, we were not creating the ingress correctly.
> Fix query ingress when using streaming strategy

- tests/e2e/Makefile
- tests/e2e/elasticsearch/Makefile
- tests/e2e/elasticsearch/render.sh
- tests/e2e/examples/Makefile
- tests/e2e/examples/render.sh
- tests/e2e/generate/render.sh
- tests/e2e/miscellaneous/render.sh
- tests/e2e/render-utils.sh
- tests/e2e/sidecar/render.sh
- tests/e2e/streaming/Makefile
- tests/e2e/streaming/render.sh
- tests/e2e/ui/render.sh
- tests/e2e/upgrade/render.sh
- tests/templates/vertex-install.yaml.template
- Currently e2e tests are not supported to run on non `x86_64` environment. due to lack of other dependent operator/images support
- Needs environment variables to filter required tests to run on a target platform. able to skip some of the tests which we can not run on the target platform at this time.
- Introduced `SKIP_KAFKA` environment variable to skip kafka/streaming related tests. default: enabled
- Updated the code to react for `SKIP_ES_EXTERNAL` variable. In Openshift if `SKIP_ES_EXTERNAL` enabled, uses self provision Elasticsearch node.
- Updated to react for custom `VERTX_IMG` variable
> add support to run the tests on multi architecture 

- tests/e2e/generate/render.sh
Disable `generate` E2E test due to #2145.
> Disable generate E2E test in OCP

- .github/workflows/base-checks.yaml
- .github/workflows/release.yaml
- .golangci.yml
- Dockerfile
- Dockerfile.asserts
- Makefile
- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- go.mod
- hack/actions/e2e/action.yaml
- hack/common.sh
- hack/ignore-createdAt-bundle.sh
- hack/install/install-kustomize.sh
- pkg/storage/cassandra_dependencies.go
- tests/e2e/miscellaneous/non-cluster-wide/00-errors.yaml
- tests/e2e/miscellaneous/non-cluster-wide/00-undeploy.yaml.template
- tests/e2e/miscellaneous/non-cluster-wide/01-install.yaml.template
- tests/e2e/miscellaneous/non-cluster-wide/03-assert.yaml
- tests/e2e/miscellaneous/non-cluster-wide/03-install.yaml.template
- tests/e2e/miscellaneous/render.sh
- tests/e2e/render-utils.sh
- Resolves #2177
- Bump the `operator-sdk` version to `1.27.0`
- Add all the required changes to make the version work
> **Note**
> Some other changes are requested in #2177. These will be addressed in another PR
> update operator-sdk to 1.27.0

- apis/v1/jaeger_types.go
- bundle/manifests/jaegertracing.io_jaegers.yaml
- config/crd/bases/jaegertracing.io_jaegers.yaml
- docs/api.md
- examples/all-in-one-with-priority-class.yaml
- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
- Resolves #1601
- Add PriorityClass capability for allinone strategy; includes unit test & example
- Please note that the make generate api path was changed to './apis/v1' in order to run the command.
> Add PriorityClass for AllInOne strategy

- tests/Dockerfile
We will be running end-to-end tests for Jaeger Operator in our [OpenShift release](https://github.com/openshift/release) using Prow CI jobs. These jobs will encompass various cluster configurations, and the Dockerfile will containerize the tests for execution within the Prow CI.
> [chore] Add Dockerfile for OpenShift containerized test execution on Prow CI.

- pkg/service/agent.go
- pkg/service/agent_test.go
- pkg/service/collector.go
- pkg/service/collector_test.go
- pkg/service/query.go
- pkg/service/query_test.go
- tests/e2e/miscellaneous/istio/03-assert.yaml
This PR was originally created by @thomaspaulin. After doing a tiny modification 754db2b4b5970cd4a3d9ea2ae228052059d71d29 and pushing it to the original branch, the pr got automatically closed :no_good: 
For more details see:
- https://github.com/jaegertracing/jaeger-operator/pull/2204
Closes https://github.com/jaegertracing/jaeger-operator/issues/2203
> Expose admin ports for agent, collector, and query Deployments via the equivalent Service

- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
- Mitigates to #1983
- Reduce the number of read/writes to viper in the different functions
- The version of the autoscaling and cronjob APIs is checked just in the start
Note this is the first PR to fix the #1983 issue.
> Refactor the autodetect module to reduce the number of writes/reads in viper configuration

- controllers/appsv1/deployment_webhook.go
- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
- Resolves #1349 
- We are checking that `JAEGER_SERVICE_NAME` or `JAEGER_PROPAGATION` is present in the envFrom configMaps , if it is present we are not adding these variables in the env variables.
> Added changes to respect env variable set from envFrom configMaps

- pkg/autodetect/main.go
- pkg/cmd/start/bootstrap.go
- Resolves #2279
- Ensure the OAuth Proxy image detection is run after the platform detection
> Ensure the OAuth Proxy image detection is run after the platform detection

- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/deployment/collector.go
- pkg/deployment/collector_test.go
- pkg/deployment/ingester.go
- pkg/deployment/ingester_test.go
- pkg/deployment/query.go
- pkg/deployment/query_test.go
-  Resolves #1531 
- We are facing this error because labels generated in the selector fields are different from the labels in the template.metadata.labels. With this PR we are generating the same labels under both sections.
> Fix custom labels for the deployable components in production strategy 

- pkg/autoclean/main.go
- pkg/autoclean/main_test.go
- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
- pkg/cmd/start/bootstrap.go
- Follow up for #2274
- Create the autoclean module
Some stuff used by the autoclean module is using `viper`. To avoid a cycle, I moved this logic outsed the `autodetect` module (since actually we were not autodetecting anything in this case).
> Move the autoclean tasks to their own module

- pkg/cronjob/es_index_cleaner.go
- pkg/cronjob/es_index_cleaner_test.go
- pkg/cronjob/es_rollover.go
- pkg/cronjob/es_rollover_test.go
- pkg/cronjob/spark_dependencies.go
- pkg/cronjob/spark_dependencies_test.go
- pkg/deployment/autoscale.go
-  Resolves #2137 
- Added missing ApiVersion and Kind for HPA and Cronjobs
> Fix apiVersion and kind are missing in jaeger-operator generate output

- pkg/autodetect/main.go
> Remove the TokenReview after checking we can create it

- apis/v1/jaeger_types.go
- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
- pkg/autodetect/operatorconfig.go
- pkg/controller/jaeger/jaeger_controller.go
- pkg/controller/jaeger/kafka_test.go
- pkg/controller/jaeger/kafkauser_test.go
- Continuation of #2278 to fix #1983
- Protect the Kafka Operator integration with a mutex.
> Protect the kafka-profision setting behind a mutex

- pkg/cronjob/es_index_cleaner.go
- pkg/cronjob/es_rollover.go
- pkg/cronjob/spark_dependencies.go
- pkg/deployment/agent.go
- pkg/deployment/all_in_one.go
- pkg/deployment/collector.go
- pkg/deployment/ingester.go
- pkg/deployment/query.go
- pkg/inject/oauth_proxy.go
- pkg/inject/sidecar.go
- pkg/storage/elasticsearch.go
- pkg/storage/elasticsearch_test.go
Docs:
- https://docs.openshift.com/container-platform/4.13/operators/operator_sdk/golang/osdk-golang-tutorial.html#osdk-run-proxy_osdk-golang-tutorial 
- https://sdk.operatorframework.io/docs/building-operators/golang/references/proxy-vars/
- https://docs.openshift.com/container-platform/4.13/networking/enable-cluster-wide-proxy.html#enable-cluster-wide-proxy
docker image: `pavolloffay/jaeger-opeator:PR2330-6`
(IMG=pavolloffay/jaeger-opeator:PR2330-4 make docker)
CRs for testing:
```
kubectl apply  -f - <<EOF
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
name: simplest
spec:
allInOne:
image: pavolloffay/all-in-one:proxy-6
EOF
kubectl apply  -f - <<EOF
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
name: simple-prod
spec:
query:
image: pavolloffay/jaeger-query:proxy-6 …
```
> Pass proxy env vars to operands

- COMPATIBILITY.md
Resolves: https://github.com/jaegertracing/jaeger-operator/issues/2331
Adds the latest 2 releases of jaeger-operator to the COMPATIBILITY.md file
The information is taken by first checking out to the tags and then for each tag:
- **Kubernetes**: Kind .yamls present in the root dir indicating the tested K8s versions
- **Strimzi Operator**: Strimzi Operator version being pulled in the Makefile
- **Cert-Manager**: From the `CERTMANAGER_VERSION` variable defined in the Makefile
> Add v1.48.x and v1.49.x to the support map

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
EnvFrom can also be used for SecretRefs in which case the existing logic would result in a nil pointer dereference.
Resolves #2341
- Add a nil check for ConfigMapRef when retrieving matched config maps for deployment
- Added appropriate unit testing for the func
- Tested on local kind minikube cluster with test deployment configs from #2341 
> Check if envFrom has ConfigMapRef set

- pkg/cmd/start/main.go
For disconnected environments, various tools expect the image location to be set in RELATED_IMAGE_ environment variables:
https://redhat-connect.gitbook.io/certified-operator-guide/troubleshooting-and-resources/offline-enabled-operators#golang-operators
https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs
- The image location of related images (jaeger-agent, jaeger-query, etc.) can be set via RELATED_IMAGE_ environment variables.
- local tests. It's a basic feature of the viper library and afaics doesn't warrant additional tests.
> Support configuring images via RELATED_IMAGE_ environment variables

- CONTRIBUTING.md
- RELEASE.md
The OpenShift CI fials for release PRs e.g. https://github.com/jaegertracing/jaeger-operator/pull/2365. We should either make it pass or document this.
> Document that the openshift CI can fail on release PR

- pkg/inject/sidecar.go
- pkg/inject/sidecar_test.go
Resolves https://issues.redhat.com/browse/TRACING-3722 
- 
With this patch the agent injection code prefers Jaeger in the same namespace. 
Before if jaeger production (with a separate jaeger-query pod that injects agent) was created in multiple namespaces the jaeger-agent injected into the query pod was overridden to the Jaeger that was return as first from the API server. 
docker image: `docker.io/pavolloffay/jaeger-operator:agent-issue-PR2383-1`
See the comment in the code
- 
> Fix injection: prefer jaeger in the same namespace

- Makefile
- RELEASE.md
- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/manifests/bases/jaeger-operator.clusterserviceversion.yaml
> Fix containerImage field and remove statement about failing CI

- .github/workflows/base-checks.yaml
- The cache of go dependencies is not working properly in base-check workflow
- Trigger checkout before setup-go
- CI
> checkout before setup-go

- .github/dependabot.yml
- The maintainer needs to wait for around 1h30 between the addition of 'ok-to-test' label and the end of the workflows executions
- This PR provides default dependabot labels plus 'ok-to-test' so it doesn't need to be added by the maintainer.
- CI
> Add ok-to-test label to dependabot merge-requests by default

- .ci/after-success.sh
- .ci/upload-test-coverage.sh
- .github/workflows/base-checks.yaml
- Dockerfile
- OSSF Scorecard conformity
-  Pin quay.io/centos/centos:stream9 Docker image version
- Use codecov/codecov-action instead of `bash <(curl -s https://codecov.io/bash)`
- Remove unused scripts (.ci/after-success.sh and .ci/upload-test-coverage.sh)
- CI
> Improve OSSF score

- apis/v1/jaeger_webhook.go
> apis/v1: add jaeger agent deprecation warning

- apis/v1/jaeger_types.go
- pkg/autodetect/main.go
- pkg/autodetect/main_test.go
- pkg/ingress/query.go
- pkg/ingress/query_test.go
- tests/assert-jobs/query/main.go
- tests/e2e/miscellaneous/cassandra-spark/01-assert.yaml.template
- tests/e2e/miscellaneous/non-cluster-wide/01-install.yaml.template
- tests/e2e/miscellaneous/non-cluster-wide/03-install.yaml.template
- tests/e2e/miscellaneous/render.sh
> Fix the CI

- COMPATIBILITY.md
Resolves https://github.com/jaegertracing/jaeger-operator/issues/2506
This PR extends the compatibility matrix by adding the missing Jaeger Operator versions.
Ran the command: `make lint test`
> Extended compatibility matrix

- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/manifests/bases/jaeger-operator.clusterserviceversion.yaml
The script didn't upgrade properly the image during some releases.
> Fix image for 1.56.0

- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
Resolve #2210 
Modify ImagePullSecrets input in agent.go definition to accept imagePullSecrets defined under agent for daemonset strategy.
Verified the changes by running TestAgentImagePullSecrets test in agent_test.go and also modified the spec referencd for ImagePullSecrets test.
> fixes [Bug]: imagePullSecrets is not set for agent DaemonSet #2210

- COMPATIBILITY.md
Resolves #2574 
Updated compatibility matrix with the following map:
| Jaeger Operator | Kubernetes      | Strimzi Operator   | Cert-Manager |
|-----------------|-----------------|--------------------|--------------|
| v1.57.x         | v1.19 to v1.28  | v0.32              | v1.6.1       |
- 
> Update compatibility matrix for v1.57.x

- CHANGELOG.md
- COMPATIBILITY.md
- RELEASE.md
- bundle/manifests/jaeger-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/jaeger-operator.clusterserviceversion.yaml
- examples/all-in-one-with-options.yaml
- examples/operator-with-tracing.yaml
- examples/statefulset-manual-sidecar.yaml
- examples/tracegen.yaml
- pkg/deployment/all_in_one_test.go
- pkg/deployment/collector_test.go
- pkg/deployment/otlp.go
- versions.txt
> Preparing release v1.59.0

- go.mod
The absence of a patch version makes some builders to fail.
> Fix golang version in go.mod

- controllers/appsv1/namespace_controller_test.go
- Missing unit test for `NamespaceReconciler`
- Adds a missing unit-test for reconciling the `NamespaceReconciler`.
- Ran the unit test locally
> feat: added unit test for namespace reconciler

- controllers/elasticsearch/elasticsearch_controller_test.go
- controllers/elasticsearch/suit_test.go
- Missing unit test for `controllers/elasticsearch`
- Adds missing unit test for `controllers/elasticsearch`
- Tested locally `make test-unit`
> feat: added missing test for elasticsearch reconciler

- apis/v1/jaeger_types.go
- apis/v1/zz_generated.deepcopy.go
- bundle/manifests/jaegertracing.io_jaegers.yaml
- config/crd/bases/jaegertracing.io_jaegers.yaml
- docs/api.md
- pkg/cmd/start/main.go
- pkg/inject/oauth_proxy.go
- pkg/inject/oauth_proxy_test.go
- pkg/route/query.go
- pkg/route/query_test.go
- 
https://issues.redhat.com/browse/TRACING-4238
- 
- 
> TRACING-4238 | Fix gatewat 502 timeout

- COMPATIBILITY.md
- resolves https://github.com/jaegertracing/jaeger-operator/issues/2724
Updated the Jaeger Operator's compatibility Matrix by following the guidance given here: https://github.com/jaegertracing/jaeger-operator/issues/2219#issuecomment-1610911287
N/A
> Added compatibility for Jaeger Operator v1.61.x and v1.62.x

- .ci/prepare-release.sh
- Dockerfile
- Makefile
- pkg/deployment/agent.go
- pkg/deployment/agent_test.go
- pkg/util/util.go
- pkg/version/main.go
- 
- 
- 
- for `jaeger-ui`: `npm run lint` and `npm run test`
> Pin agent version to 1.62.0

- apis/v1/jaeger_webhook.go
- apis/v1/jaeger_webhook_test.go
Resolves #2794
Moved the webhook interface validation code from `jaeger_webhook.go` to `jaeger_webhook_test.go` to ensure the Jaeger structure still fulfills the webhook interfaces. This change allows external projects to import the `jaeger-operator/apis/v1` package with `sigs.k8s.io/controller-runtime` library version [v0.20.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.20.0), as the deprecated webhook interfaces were removed in this version. 
- I created a tag over this MR (on my forked repo) and I was able to build and run succesfully the `jaeger-operator/apis/v1` package with the `sigs.k8s.io/controller-runtime` library version [v0.20.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.20.0) over an external Go Kubernetes operator …
> refactor: move webhook interface validation to test file

- README.md
Added documentation for using Jaeger V2 in-memory config with OpenTelemetry Operator
- Gives users a way to interact with Jaeger V2 UI with the help of OpenTelemetry Operator
- Documenting the process of deploying Jaeger V2 with OpenTelemetry Operator
- Tested locally on a `Kind` cluster
> Added documentation for using Jaeger V2 in-memory config with OpenTelemetry Operator

- pkg/config/tls/tls_test.go
- pkg/deployment/all_in_one.go
- pkg/deployment/all_in_one_test.go
-  When agent was removed from jaeger , reporter flags were removed from all in one binary. so those flags are not valid anymore.
-  Remove reporter flags, as those are specific flags for report to the agent. which is not anymore present in the all in one.
-  Deployed on kubernetes cluster and did an all in one deployment
- for `jaeger-ui`: `npm run lint` and `npm run test`
> Remove reporter (agent) flags from all in one
